#!/command/with-contenv sh
set -eu

services_dir="/etc/services.d"
available_dir="/etc/xian-services.d"

mkdir -p "${services_dir}" /root
if [ ! -d /root/.cometbft ]; then
  mkdir -p /root/.cometbft
fi
mkdir -p /root/.cometbft/xian 2>/dev/null || true
rm -rf "${services_dir:?}/"*
ln -s "${available_dir}/xian" "${services_dir}/xian"
ln -s "${available_dir}/cometbft" "${services_dir}/cometbft"

rm -f /tmp/abci.sock
