services:
  contracting:
    hostname: contracting-dev-shell
    build: 
      context: .
      dockerfile: ./docker/contracting.Dockerfile
    volumes:
      - ${XIAN_CONTRACTING_DIR}:/usr/src/app/xian-contracting
      - ${XIAN_PY_DIR}:/usr/src/app/xian-py
      - ${XIAN_CONTRACTS_DIR}:/usr/src/app/contracts
    stdin_open: true
    tty: true
    command: >
      bash -lc "pip install -e ./xian-py && pip install -e ./xian-contracting && tail -f /dev/null"
