DOCKER_COMPOSE ?= docker compose
STACK_DIR := $(abspath .)

XIAN_STACK_SECRETS_ENV ?= $(STACK_DIR)/.stack-secrets.env

define stack_secret
$(strip $(shell XIAN_STACK_SECRETS_ENV='$(abspath $(XIAN_STACK_SECRETS_ENV))' bash -lc 'source ./scripts/stack-env.sh >/dev/null 2>&1; ensure_stack_secrets_env >/dev/null; printf "%s" "$${$(1)}"'))
endef

XIAN_CLI_DIR ?= ../xian-cli
XIAN_ABCI_DIR ?= ../xian-abci
XIAN_CONFIGS_DIR ?= ../xian-configs
XIAN_CONTRACTING_DIR ?= ../xian-contracting
XIAN_PY_DIR ?= ../xian-py
XIAN_DEX_CONTRACTS_DIR ?= ../xian-contracts/contracts/dex/src
XIAN_DEX_BOOTSTRAP_RPC_URL ?=
XIAN_DEX_BOOTSTRAP_CHAIN_ID ?=
XIAN_DEX_DEPLOYER_PRIVATE_KEY ?=
XIAN_DEX_VALIDATOR_KEY_PATH ?= ./.cometbft/config/priv_validator_key.json
XIAN_STACK_PYTHON ?= 3.14
XIAN_SERVICE_NODE ?= 0
XIAN_COMETBFT_HOME ?= ./.cometbft
XIAN_BDS_DATA_DIR ?= ./.bds.db
XIAN_BDS_HOST ?= postgres
XIAN_BDS_PORT ?= 5432
XIAN_BDS_DATABASE ?= xian
XIAN_BDS_USER ?= xian
XIAN_BDS_PASSWORD ?= $(call stack_secret,XIAN_BDS_PASSWORD)
XIAN_BDS_POOL_MIN_SIZE ?= 1
XIAN_BDS_POOL_MAX_SIZE ?= 10
XIAN_BDS_STATEMENT_TIMEOUT_MS ?= 0
XIAN_BDS_APPLICATION_NAME ?= xian-bds
XIAN_BDS_SPOOL_DIR ?=
XIAN_BDS_SPOOL_WARN_ENTRIES ?= 256
XIAN_BDS_SPOOL_WARN_BYTES ?= 536870912
XIAN_BDS_DISK_FREE_WARN_BYTES ?= 2147483648
XIAN_BDS_SNAPSHOT_PATH ?= $(XIAN_COMETBFT_HOME)/snapshots/xian-bds-snapshot.tar.gz
XIAN_BDS_SNAPSHOT_FORCE ?= 0
XIAN_BDS_SNAPSHOT_CLEAR_SPOOL ?= 0
XIAN_STACK_DISK_FREE_WARN_BYTES ?= 10737418240
XIAN_CONTRACTS_DIR ?= ./contracts
XIAN_COMETBFT_VERSION ?= 0.39.1
XIAN_S6_OVERLAY_VERSION ?= 3.2.1.0
XIAN_S6_VERBOSITY ?= 1
XIAN_TRACER_MODE ?= python_line_v1
XIAN_NODE_IMAGE_MODE ?= local_build
XIAN_NODE_INTEGRATED_IMAGE ?= xian-node-integrated:local
XIAN_NODE_SPLIT_IMAGE ?= xian-node-split:local
XIAN_PUBLIC_RPC_ENABLED ?= 0
XIAN_PUBLIC_QUERY_ENABLED ?= 0
XIAN_PUBLIC_METRICS_ENABLED ?= 0
XIAN_COMETBFT_RPC_HOST ?= 127.0.0.1
XIAN_COMETBFT_RPC_PORT ?= 26657
XIAN_COMETBFT_P2P_HOST ?= 0.0.0.0
XIAN_COMETBFT_P2P_PORT ?= 26656
XIAN_COMETBFT_METRICS_HOST ?= 127.0.0.1
XIAN_COMETBFT_METRICS_PORT ?= 26660
XIAN_APP_METRICS_ENABLED ?= 1
XIAN_APP_METRICS_LISTEN_HOST ?= 0.0.0.0
XIAN_APP_METRICS_HOST ?= 127.0.0.1
XIAN_APP_METRICS_PORT ?= 9108
XIAN_APP_METRICS_BDS_REFRESH_SECONDS ?= 5.0
XIAN_PERF_ENABLED ?= 1
XIAN_PERF_RECENT_BLOCKS ?= 64
XIAN_PROMETHEUS_IMAGE ?= prom/prometheus:v3.10.0
XIAN_PROMETHEUS_CONFIG ?= ./monitoring/prometheus/integrated.yml
XIAN_PROMETHEUS_HOST ?= 127.0.0.1
XIAN_PROMETHEUS_PORT ?= 9090
XIAN_GRAFANA_IMAGE ?= grafana/grafana:12.2.0
XIAN_GRAFANA_HOST ?= 127.0.0.1
XIAN_GRAFANA_PORT ?= 3000
XIAN_STACK_TOPOLOGY ?= integrated
XIAN_DOCKER_ABCI_MEMORY_LIMIT ?= 2048m
XIAN_DOCKER_ABCI_MEMORY_RESERVATION ?= 1024m
XIAN_DOCKER_ABCI_MEMORY_SWAP ?= 2048m
XIAN_DOCKER_ABCI_PIDS_LIMIT ?= 512
XIAN_DOCKER_ABCI_NOFILE_SOFT ?= 65536
XIAN_DOCKER_ABCI_NOFILE_HARD ?= 65536
XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT ?= 1536m
XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION ?= 768m
XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP ?= 1536m
XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT ?= 384
XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT ?= 65536
XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD ?= 65536
XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT ?= 768m
XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION ?= 256m
XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP ?= 768m
XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT ?= 256
XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT ?= 65536
XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD ?= 65536
XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT ?= 512m
XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION ?= 256m
XIAN_DOCKER_DASHBOARD_MEMORY_SWAP ?= 512m
XIAN_DOCKER_DASHBOARD_PIDS_LIMIT ?= 256
XIAN_DOCKER_DASHBOARD_NOFILE_SOFT ?= 65536
XIAN_DOCKER_DASHBOARD_NOFILE_HARD ?= 65536
XIAN_DASHBOARD_HOST ?= 127.0.0.1
XIAN_DASHBOARD_PORT ?= 8080
XIAN_DOCKER_POSTGRES_MEMORY_LIMIT ?= 1024m
XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION ?= 512m
XIAN_DOCKER_POSTGRES_MEMORY_SWAP ?= 1024m
XIAN_DOCKER_POSTGRES_PIDS_LIMIT ?= 256
XIAN_DOCKER_POSTGRES_NOFILE_SOFT ?= 65536
XIAN_DOCKER_POSTGRES_NOFILE_HARD ?= 65536
XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT ?= 768m
XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION ?= 256m
XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP ?= 768m
XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT ?= 256
XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT ?= 65536
XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD ?= 65536
XIAN_POSTGRAPHILE_USER ?= xian_graphql
XIAN_POSTGRAPHILE_PASSWORD ?= $(call stack_secret,XIAN_POSTGRAPHILE_PASSWORD)
XIAN_POSTGRAPHILE_HOST ?= 127.0.0.1
XIAN_POSTGRAPHILE_PORT ?= 5000
XIAN_LOCALNET_TOPOLOGY ?= integrated
XIAN_LOCALNET_GENESIS_NETWORK ?= local
XIAN_LOCALNET_TRACER_MODE ?= $(XIAN_TRACER_MODE)
XIAN_LOCALNET_EXECUTION_MODE ?=
XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION ?=
XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE ?=
XIAN_LOCALNET_EXECUTION_AUTHORITY ?=
XIAN_LOCALNET_EXECUTION_SHADOW_TRACER_MODE ?=
XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED ?= 0
XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS ?= 4
XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS ?= 8
XIAN_LOCALNET_PROFILE ?= default
XIAN_LOCALNET_BLOCK_POLICY_MODE ?=
XIAN_LOCALNET_BLOCK_POLICY_INTERVAL ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE_DELTA ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE_DELTA ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT_DELTA ?=
XIAN_LOCALNET_CONSENSUS_TIMEOUT_COMMIT ?=
XIAN_LOCALNET_SKIP_TIMEOUT_COMMIT ?=
XIAN_LOCALNET_NODE_MEMORY_LIMIT ?= 1536m
XIAN_LOCALNET_NODE_MEMORY_RESERVATION ?= 1024m
XIAN_LOCALNET_NODE_MEMORY_SWAP ?= 1536m
XIAN_LOCALNET_NODE_PIDS_LIMIT ?= 512
XIAN_LOCALNET_NODE_NOFILE_SOFT ?= 65536
XIAN_LOCALNET_NODE_NOFILE_HARD ?= 65536
XIAN_LOCALNET_ABCI_MEMORY_LIMIT ?= 1024m
XIAN_LOCALNET_ABCI_MEMORY_RESERVATION ?= 768m
XIAN_LOCALNET_ABCI_MEMORY_SWAP ?= 1024m
XIAN_LOCALNET_ABCI_PIDS_LIMIT ?= 384
XIAN_LOCALNET_ABCI_NOFILE_SOFT ?= 65536
XIAN_LOCALNET_ABCI_NOFILE_HARD ?= 65536
XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT ?= 512m
XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION ?= 256m
XIAN_LOCALNET_COMETBFT_MEMORY_SWAP ?= 512m
XIAN_LOCALNET_COMETBFT_PIDS_LIMIT ?= 256
XIAN_LOCALNET_COMETBFT_NOFILE_SOFT ?= 65536
XIAN_LOCALNET_COMETBFT_NOFILE_HARD ?= 65536

export XIAN_CLI_DIR := $(abspath $(XIAN_CLI_DIR))
export XIAN_ABCI_DIR := $(abspath $(XIAN_ABCI_DIR))
export XIAN_CONFIGS_DIR := $(abspath $(XIAN_CONFIGS_DIR))
export XIAN_CONTRACTING_DIR := $(abspath $(XIAN_CONTRACTING_DIR))
export XIAN_PY_DIR := $(abspath $(XIAN_PY_DIR))
export XIAN_DEX_CONTRACTS_DIR := $(abspath $(XIAN_DEX_CONTRACTS_DIR))
export XIAN_DEX_DEPLOYER_PRIVATE_KEY := $(XIAN_DEX_DEPLOYER_PRIVATE_KEY)
export XIAN_DEX_VALIDATOR_KEY_PATH := $(abspath $(XIAN_DEX_VALIDATOR_KEY_PATH))
export XIAN_STACK_SECRETS_ENV := $(abspath $(XIAN_STACK_SECRETS_ENV))
export XIAN_SERVICE_NODE := $(XIAN_SERVICE_NODE)
export XIAN_COMETBFT_HOME := $(abspath $(XIAN_COMETBFT_HOME))
export XIAN_BDS_DATA_DIR := $(abspath $(XIAN_BDS_DATA_DIR))
export XIAN_BDS_HOST := $(XIAN_BDS_HOST)
export XIAN_BDS_PORT := $(XIAN_BDS_PORT)
export XIAN_BDS_DATABASE := $(XIAN_BDS_DATABASE)
export XIAN_BDS_USER := $(XIAN_BDS_USER)
export XIAN_BDS_PASSWORD := $(XIAN_BDS_PASSWORD)
export XIAN_BDS_POOL_MIN_SIZE := $(XIAN_BDS_POOL_MIN_SIZE)
export XIAN_BDS_POOL_MAX_SIZE := $(XIAN_BDS_POOL_MAX_SIZE)
export XIAN_BDS_STATEMENT_TIMEOUT_MS := $(XIAN_BDS_STATEMENT_TIMEOUT_MS)
export XIAN_BDS_APPLICATION_NAME := $(XIAN_BDS_APPLICATION_NAME)
export XIAN_BDS_SPOOL_DIR := $(XIAN_BDS_SPOOL_DIR)
export XIAN_BDS_SPOOL_WARN_ENTRIES := $(XIAN_BDS_SPOOL_WARN_ENTRIES)
export XIAN_BDS_SPOOL_WARN_BYTES := $(XIAN_BDS_SPOOL_WARN_BYTES)
export XIAN_BDS_DISK_FREE_WARN_BYTES := $(XIAN_BDS_DISK_FREE_WARN_BYTES)
export XIAN_BDS_SNAPSHOT_PATH := $(abspath $(XIAN_BDS_SNAPSHOT_PATH))
export XIAN_BDS_SNAPSHOT_FORCE := $(XIAN_BDS_SNAPSHOT_FORCE)
export XIAN_BDS_SNAPSHOT_CLEAR_SPOOL := $(XIAN_BDS_SNAPSHOT_CLEAR_SPOOL)
export XIAN_STACK_DISK_FREE_WARN_BYTES := $(XIAN_STACK_DISK_FREE_WARN_BYTES)
export XIAN_CONTRACTS_DIR := $(abspath $(XIAN_CONTRACTS_DIR))
export XIAN_COMETBFT_VERSION := $(XIAN_COMETBFT_VERSION)
export XIAN_S6_OVERLAY_VERSION := $(XIAN_S6_OVERLAY_VERSION)
export XIAN_S6_VERBOSITY := $(XIAN_S6_VERBOSITY)
export XIAN_TRACER_MODE := $(XIAN_TRACER_MODE)
export XIAN_NODE_IMAGE_MODE := $(XIAN_NODE_IMAGE_MODE)
export XIAN_NODE_INTEGRATED_IMAGE := $(XIAN_NODE_INTEGRATED_IMAGE)
export XIAN_NODE_SPLIT_IMAGE := $(XIAN_NODE_SPLIT_IMAGE)
export XIAN_PUBLIC_RPC_ENABLED := $(XIAN_PUBLIC_RPC_ENABLED)
export XIAN_PUBLIC_QUERY_ENABLED := $(XIAN_PUBLIC_QUERY_ENABLED)
export XIAN_PUBLIC_METRICS_ENABLED := $(XIAN_PUBLIC_METRICS_ENABLED)
export XIAN_COMETBFT_RPC_HOST := $(XIAN_COMETBFT_RPC_HOST)
export XIAN_COMETBFT_RPC_PORT := $(XIAN_COMETBFT_RPC_PORT)
export XIAN_COMETBFT_P2P_HOST := $(XIAN_COMETBFT_P2P_HOST)
export XIAN_COMETBFT_P2P_PORT := $(XIAN_COMETBFT_P2P_PORT)
export XIAN_COMETBFT_METRICS_HOST := $(XIAN_COMETBFT_METRICS_HOST)
export XIAN_COMETBFT_METRICS_PORT := $(XIAN_COMETBFT_METRICS_PORT)
export XIAN_APP_METRICS_ENABLED := $(XIAN_APP_METRICS_ENABLED)
export XIAN_APP_METRICS_LISTEN_HOST := $(XIAN_APP_METRICS_LISTEN_HOST)
export XIAN_APP_METRICS_HOST := $(XIAN_APP_METRICS_HOST)
export XIAN_APP_METRICS_PORT := $(XIAN_APP_METRICS_PORT)
export XIAN_APP_METRICS_BDS_REFRESH_SECONDS := $(XIAN_APP_METRICS_BDS_REFRESH_SECONDS)
export XIAN_PERF_ENABLED := $(XIAN_PERF_ENABLED)
export XIAN_PERF_RECENT_BLOCKS := $(XIAN_PERF_RECENT_BLOCKS)
export XIAN_PROMETHEUS_IMAGE := $(XIAN_PROMETHEUS_IMAGE)
export XIAN_PROMETHEUS_CONFIG := $(XIAN_PROMETHEUS_CONFIG)
export XIAN_PROMETHEUS_HOST := $(XIAN_PROMETHEUS_HOST)
export XIAN_PROMETHEUS_PORT := $(XIAN_PROMETHEUS_PORT)
export XIAN_GRAFANA_IMAGE := $(XIAN_GRAFANA_IMAGE)
export XIAN_GRAFANA_HOST := $(XIAN_GRAFANA_HOST)
export XIAN_GRAFANA_PORT := $(XIAN_GRAFANA_PORT)
export XIAN_STACK_TOPOLOGY := $(XIAN_STACK_TOPOLOGY)
export XIAN_DOCKER_ABCI_MEMORY_LIMIT := $(XIAN_DOCKER_ABCI_MEMORY_LIMIT)
export XIAN_DOCKER_ABCI_MEMORY_RESERVATION := $(XIAN_DOCKER_ABCI_MEMORY_RESERVATION)
export XIAN_DOCKER_ABCI_MEMORY_SWAP := $(XIAN_DOCKER_ABCI_MEMORY_SWAP)
export XIAN_DOCKER_ABCI_PIDS_LIMIT := $(XIAN_DOCKER_ABCI_PIDS_LIMIT)
export XIAN_DOCKER_ABCI_NOFILE_SOFT := $(XIAN_DOCKER_ABCI_NOFILE_SOFT)
export XIAN_DOCKER_ABCI_NOFILE_HARD := $(XIAN_DOCKER_ABCI_NOFILE_HARD)
export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT := $(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT)
export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION := $(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION)
export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP := $(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP)
export XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT := $(XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT)
export XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT := $(XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT)
export XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD := $(XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD)
export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT := $(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT)
export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION := $(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION)
export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP := $(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP)
export XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT := $(XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT)
export XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT := $(XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT)
export XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD := $(XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD)
export XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT := $(XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT)
export XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION := $(XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION)
export XIAN_DOCKER_DASHBOARD_MEMORY_SWAP := $(XIAN_DOCKER_DASHBOARD_MEMORY_SWAP)
export XIAN_DOCKER_DASHBOARD_PIDS_LIMIT := $(XIAN_DOCKER_DASHBOARD_PIDS_LIMIT)
export XIAN_DOCKER_DASHBOARD_NOFILE_SOFT := $(XIAN_DOCKER_DASHBOARD_NOFILE_SOFT)
export XIAN_DOCKER_DASHBOARD_NOFILE_HARD := $(XIAN_DOCKER_DASHBOARD_NOFILE_HARD)
export XIAN_DASHBOARD_HOST := $(XIAN_DASHBOARD_HOST)
export XIAN_DASHBOARD_PORT := $(XIAN_DASHBOARD_PORT)
export XIAN_DOCKER_POSTGRES_MEMORY_LIMIT := $(XIAN_DOCKER_POSTGRES_MEMORY_LIMIT)
export XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION := $(XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION)
export XIAN_DOCKER_POSTGRES_MEMORY_SWAP := $(XIAN_DOCKER_POSTGRES_MEMORY_SWAP)
export XIAN_DOCKER_POSTGRES_PIDS_LIMIT := $(XIAN_DOCKER_POSTGRES_PIDS_LIMIT)
export XIAN_DOCKER_POSTGRES_NOFILE_SOFT := $(XIAN_DOCKER_POSTGRES_NOFILE_SOFT)
export XIAN_DOCKER_POSTGRES_NOFILE_HARD := $(XIAN_DOCKER_POSTGRES_NOFILE_HARD)
export XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT := $(XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT)
export XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION := $(XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION)
export XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP := $(XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP)
export XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT := $(XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT)
export XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT := $(XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT)
export XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD := $(XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD)
export XIAN_POSTGRAPHILE_USER := $(XIAN_POSTGRAPHILE_USER)
export XIAN_POSTGRAPHILE_PASSWORD := $(XIAN_POSTGRAPHILE_PASSWORD)
export XIAN_POSTGRAPHILE_HOST := $(XIAN_POSTGRAPHILE_HOST)
export XIAN_POSTGRAPHILE_PORT := $(XIAN_POSTGRAPHILE_PORT)
export XIAN_LOCALNET_TOPOLOGY := $(XIAN_LOCALNET_TOPOLOGY)
export XIAN_LOCALNET_TRACER_MODE := $(XIAN_LOCALNET_TRACER_MODE)
export XIAN_LOCALNET_EXECUTION_MODE := $(XIAN_LOCALNET_EXECUTION_MODE)
export XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION := $(XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION)
export XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE := $(XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE)
export XIAN_LOCALNET_EXECUTION_AUTHORITY := $(XIAN_LOCALNET_EXECUTION_AUTHORITY)
export XIAN_LOCALNET_EXECUTION_SHADOW_TRACER_MODE := $(XIAN_LOCALNET_EXECUTION_SHADOW_TRACER_MODE)
export XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED := $(XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED)
export XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS := $(XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS)
export XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS := $(XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS)
export XIAN_LOCALNET_PROFILE := $(XIAN_LOCALNET_PROFILE)
export XIAN_LOCALNET_BLOCK_POLICY_MODE := $(XIAN_LOCALNET_BLOCK_POLICY_MODE)
export XIAN_LOCALNET_BLOCK_POLICY_INTERVAL := $(XIAN_LOCALNET_BLOCK_POLICY_INTERVAL)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE_DELTA := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PROPOSE_DELTA)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE_DELTA := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PREVOTE_DELTA)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT_DELTA := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_PRECOMMIT_DELTA)
export XIAN_LOCALNET_CONSENSUS_TIMEOUT_COMMIT := $(XIAN_LOCALNET_CONSENSUS_TIMEOUT_COMMIT)
export XIAN_LOCALNET_SKIP_TIMEOUT_COMMIT := $(XIAN_LOCALNET_SKIP_TIMEOUT_COMMIT)
export XIAN_LOCALNET_NODE_MEMORY_LIMIT := $(XIAN_LOCALNET_NODE_MEMORY_LIMIT)
export XIAN_LOCALNET_NODE_MEMORY_RESERVATION := $(XIAN_LOCALNET_NODE_MEMORY_RESERVATION)
export XIAN_LOCALNET_NODE_MEMORY_SWAP := $(XIAN_LOCALNET_NODE_MEMORY_SWAP)
export XIAN_LOCALNET_NODE_PIDS_LIMIT := $(XIAN_LOCALNET_NODE_PIDS_LIMIT)
export XIAN_LOCALNET_NODE_NOFILE_SOFT := $(XIAN_LOCALNET_NODE_NOFILE_SOFT)
export XIAN_LOCALNET_NODE_NOFILE_HARD := $(XIAN_LOCALNET_NODE_NOFILE_HARD)
export XIAN_LOCALNET_ABCI_MEMORY_LIMIT := $(XIAN_LOCALNET_ABCI_MEMORY_LIMIT)
export XIAN_LOCALNET_ABCI_MEMORY_RESERVATION := $(XIAN_LOCALNET_ABCI_MEMORY_RESERVATION)
export XIAN_LOCALNET_ABCI_MEMORY_SWAP := $(XIAN_LOCALNET_ABCI_MEMORY_SWAP)
export XIAN_LOCALNET_ABCI_PIDS_LIMIT := $(XIAN_LOCALNET_ABCI_PIDS_LIMIT)
export XIAN_LOCALNET_ABCI_NOFILE_SOFT := $(XIAN_LOCALNET_ABCI_NOFILE_SOFT)
export XIAN_LOCALNET_ABCI_NOFILE_HARD := $(XIAN_LOCALNET_ABCI_NOFILE_HARD)
export XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT := $(XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT)
export XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION := $(XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION)
export XIAN_LOCALNET_COMETBFT_MEMORY_SWAP := $(XIAN_LOCALNET_COMETBFT_MEMORY_SWAP)
export XIAN_LOCALNET_COMETBFT_PIDS_LIMIT := $(XIAN_LOCALNET_COMETBFT_PIDS_LIMIT)
export XIAN_LOCALNET_COMETBFT_NOFILE_SOFT := $(XIAN_LOCALNET_COMETBFT_NOFILE_SOFT)
export XIAN_LOCALNET_COMETBFT_NOFILE_HARD := $(XIAN_LOCALNET_COMETBFT_NOFILE_HARD)

ABCI_COMPOSE = XIAN_SERVICE_NODE=0 $(DOCKER_COMPOSE) --profile integrated -f docker-compose-abci.yml
ABCI_BDS_COMPOSE = XIAN_SERVICE_NODE=1 $(DOCKER_COMPOSE) --profile integrated -f docker-compose-abci.yml -f docker-compose-abci-bds.yml
ABCI_FIDELITY_COMPOSE = XIAN_SERVICE_NODE=0 $(DOCKER_COMPOSE) --profile fidelity -f docker-compose-abci.yml
ABCI_DEV_COMPOSE = $(DOCKER_COMPOSE) -f docker-compose-abci-dev.yml -f docker-compose-abci-bds.yml
CONTRACTING_COMPOSE = $(DOCKER_COMPOSE) -f docker-compose-contracting.yml
LOCALNET_COMPOSE = $(DOCKER_COMPOSE) -f docker-compose-localnet.yml
NODE_UP_BUILD_FLAG = $(if $(filter registry,$(XIAN_NODE_IMAGE_MODE)),--no-build,)
DASHBOARD_UP_BUILD_FLAG = $(if $(filter registry,$(XIAN_NODE_IMAGE_MODE)),--no-build,--build)

define maybe_pull_integrated
	@if [ "$(XIAN_NODE_IMAGE_MODE)" = "registry" ]; then \
		$(1) pull $(2); \
	fi
endef

define maybe_pull_fidelity
	@if [ "$(XIAN_NODE_IMAGE_MODE)" = "registry" ]; then \
		$(1) pull $(2); \
	fi
endef

define maybe_build_postgraphile
	@if [ "$(XIAN_NODE_IMAGE_MODE)" = "registry" ]; then \
		$(1) build postgraphile; \
	fi
endef

LOCALNET_NODES ?= 4
LOCALNET_BUILD_SERVICE ?= $(if $(filter integrated,$(XIAN_LOCALNET_TOPOLOGY)),node-0,node-0-abci)
LOCALNET_MEMWATCH_MINUTES ?= 10
LOCALNET_LEAK_HUNT_MINUTES ?= 10
LOCALNET_COUNTER_OPS ?= 180
LOCALNET_DEX_ROUNDS ?= 6
LOCALNET_THROUGHPUT_OPS ?= 12000
LOCALNET_WORKLOAD_WALLET_COUNT ?= 64
LOCALNET_SUBMIT_WORKERS ?= 128
LOCALNET_BROADCAST_MODE ?= checktx
LOCALNET_RECEIPT_TIMEOUT_SECONDS ?= 45
LOCALNET_HEAVY_ROUNDS ?= 64
LOCALNET_STATE_SAMPLE_NODES ?= 2
LOCALNET_APP_HASH_WINDOW ?= 3
LOCALNET_WORKLOAD_SEED ?= xian-localnet-workload-v1
LOCALNET_WORKLOAD_SCENARIO ?= counter_basic
LOCALNET_RECEIPT_RESOLUTION ?= serial
LOCALNET_RECEIPT_WORKERS ?= 16
LOCALNET_WORKLOAD_MEASURE_MEMORY ?= 1
LOCALNET_DEX_DEPLOY_HELPER ?= 1
LOCALNET_DEX_SEED_DEMO_POOL ?= 1
LOCALNET_DEX_TOP_UP_LIQUIDITY ?= 0
LOCALNET_DEX_EMIT_TEST_SWAP ?= 0
LOCALNET_DEX_DEMO_TOKEN_CONTRACT ?= con_dex_demo_token
LOCALNET_DEX_DEMO_LP_CONTRACT ?= con_dex_demo_lp
LOCALNET_DEX_DEMO_TOKEN_NAME ?= Xian DEX Demo Token
LOCALNET_DEX_DEMO_TOKEN_SYMBOL ?= XDT
LOCALNET_DEX_DEMO_TOKEN_SUPPLY ?= 1000000
LOCALNET_DEX_DEMO_TOKEN_PRECISION ?= 8
LOCALNET_DEX_LIQUIDITY_CURRENCY_AMOUNT ?= 10000
LOCALNET_DEX_LIQUIDITY_DEMO_TOKEN_AMOUNT ?= 10000
LOCALNET_DEX_TEST_SWAP_AMOUNT ?= 10
LOCALNET_TPS_BENCH_NODES ?= 5
LOCALNET_TPS_BENCH_PORT_OFFSET ?= 1000
LOCALNET_TPS_BENCH_PROFILE ?= throughput
LOCALNET_TPS_BENCH_SCENARIO ?= both
LOCALNET_TPS_BENCH_OPS ?= 4000 8000 12000 16000
LOCALNET_TPS_BENCH_WALLET_COUNT ?= 64
LOCALNET_TPS_BENCH_SUBMIT_WORKERS ?= 128
LOCALNET_TPS_BENCH_RECEIPT_WORKERS ?= 128
LOCALNET_TPS_BENCH_RECEIPT_TIMEOUT_SECONDS ?= 90
LOCALNET_TPS_BENCH_HEAVY_ROUNDS ?= 64
LOCALNET_E2E_BOOTSTRAP ?= 1
LOCALNET_E2E_BUILD ?= 1
LOCALNET_E2E_NODES ?= 5
LOCALNET_E2E_GENESIS_NETWORK ?= testnet
LOCALNET_E2E_BDS_NODE_INDEX ?= 0
XIAN_BDS_SNAPSHOT_CONTAINER_PATH = $(patsubst $(abspath $(XIAN_COMETBFT_HOME))%,/root/.cometbft%,$(abspath $(XIAN_BDS_SNAPSHOT_PATH)))
LOCALNET_E2E_PORT_OFFSET ?= 1000
LOCALNET_E2E_SEED ?= xian-localnet-testnet-e2e-v1
LOCALNET_E2E_LOG_LEVEL ?= INFO
LOCALNET_E2E_RPC_TIMEOUT_SECONDS ?= 180
LOCALNET_E2E_STATE_SAMPLE_NODES ?= 5
LOCALNET_E2E_APP_HASH_WINDOW ?= 5
LOCALNET_E2E_RECEIPT_WORKERS ?= 24
LOCALNET_E2E_PERIODIC_ROUNDS ?= 8
LOCALNET_E2E_PERIODIC_INTERVAL_SECONDS ?= 0.35
LOCALNET_E2E_BURST_COUNTER_OPS ?= 260
LOCALNET_E2E_DEX_ROUNDS ?= 8
LOCALNET_E2E_CHAOS_CYCLES ?= 2
LOCALNET_E2E_CHAOS_LOAD_TRANSACTIONS ?= 8
LOCALNET_E2E_SOAK_DURATION_SECONDS ?= 90
LOCALNET_E2E_SOAK_BATCH_SIZE ?= 9
LOCALNET_E2E_SOAK_PROGRESS_INTERVAL_SECONDS ?= 20
LOCALNET_E2E_PARALLEL_EXECUTION_ENABLED ?= 1
LOCALNET_E2E_PARALLEL_EXECUTION_WORKERS ?= 4
LOCALNET_E2E_PARALLEL_EXECUTION_MIN_TRANSACTIONS ?= 8
LOCALNET_VM_E2E_PARALLEL_EXECUTION_MIN_TRANSACTIONS ?= 4
LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_ENABLED ?= $(XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED)
LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_WORKERS ?= $(XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS)
LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_MIN_TRANSACTIONS ?= $(XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS)
LOCALNET_VM_REPORT_MAX_SHADOW_MISMATCHES ?= 0
LOCALNET_VM_E2E_EXECUTION_MODE ?= xian_vm_v1
LOCALNET_VM_E2E_BYTECODE_VERSION ?= xvm-1
LOCALNET_VM_E2E_GAS_SCHEDULE ?= xvm-gas-1
LOCALNET_VM_E2E_AUTHORITY ?= native
LOCALNET_VALIDATOR_GOVERNANCE_BOOTSTRAP ?= 1
LOCALNET_VALIDATOR_GOVERNANCE_BUILD ?= 0
LOCALNET_VALIDATOR_GOVERNANCE_NODES ?= 5
LOCALNET_VALIDATOR_GOVERNANCE_PORT_OFFSET ?= 1000
LOCALNET_VALIDATOR_GOVERNANCE_SEED ?= xian-localnet-testnet-governance-v1
LOCALNET_VALIDATOR_GOVERNANCE_LOG_LEVEL ?= INFO
LOCALNET_VALIDATOR_GOVERNANCE_RPC_TIMEOUT_SECONDS ?= 180
LOCALNET_VALIDATOR_GOVERNANCE_GENESIS_NETWORK ?= testnet

.DEFAULT_GOAL := help

.PHONY: help print-env validate release-safety smoke smoke-cli guard-stack-security prepare-dirs \
	dev-contracting-shell dev-contracting-up dev-contracting-build dev-contracting-down \
	dev-abci-build dev-abci-up dev-abci-down dev-abci-shell \
	abci-build abci-up abci-down abci-fidelity-build abci-fidelity-up abci-fidelity-down dev-base-abci-shell \
	dashboard-build dashboard-up dashboard-down dashboard-bds-up dashboard-bds-down dashboard-fidelity-build dashboard-fidelity-up dashboard-fidelity-down \
	monitoring-up monitoring-down monitoring-bds-up monitoring-bds-down monitoring-fidelity-up monitoring-fidelity-down \
	abci-bds-build abci-bds-up abci-bds-down dev-bds-abci-shell \
	wipe-bds node-wipe node-wipe-all node-reset \
	node-stop node-start node-start-bds node-init node-configure node-id \
	node-status node-status-fidelity bds-postgres-up bds-snapshot-export bds-snapshot-import \
	storage-report \
	localnet-init localnet-build localnet-up localnet-down localnet-status \
	localnet-workload localnet-burst localnet-memwatch localnet-leak-hunt localnet-e2e localnet-vm-report localnet-vm-e2e localnet-vm-tps-bench localnet-validator-governance \
	localnet-clean localnet-logs localnet-shell

help:
	@printf "Available targets:\n"
	@printf "  %-24s %s\n" "print-env" "Show resolved workspace and data paths"
	@printf "  %-24s %s\n" "guard-stack-security" "Validate hardened stack exposure and secret settings"
	@printf "  %-24s %s\n" "validate" "Validate compose topology and required local paths"
	@printf "  %-24s %s\n" "release-safety" "Run the cross-repo release gate, including repo validation and localnet safety checks"
	@printf "  %-24s %s\n" "smoke" "Run the smallest real ABCI bring-up and shutdown path"
	@printf "  %-24s %s\n" "smoke-cli" "Run the cross-repo operator flow through xian-cli"
	@printf "  %-24s %s\n" "abci-build" "Build the default integrated node image"
	@printf "  %-24s %s\n" "abci-up" "Start the integrated node runtime container"
	@printf "  %-24s %s\n" "abci-down" "Stop the integrated node runtime container"
	@printf "  %-24s %s\n" "abci-fidelity-build" "Build the split ABCI/CometBFT fidelity images"
	@printf "  %-24s %s\n" "abci-fidelity-up" "Start the split fidelity runtime"
	@printf "  %-24s %s\n" "abci-fidelity-down" "Stop the split fidelity runtime"
	@printf "  %-24s %s\n" "dashboard-build" "Build the optional integrated dashboard image"
	@printf "  %-24s %s\n" "dashboard-up" "Start the optional integrated dashboard service"
	@printf "  %-24s %s\n" "dashboard-down" "Stop the optional integrated dashboard service"
	@printf "  %-24s %s\n" "dashboard-bds-up" "Start the optional dashboard with integrated BDS mode"
	@printf "  %-24s %s\n" "dashboard-bds-down" "Stop the optional dashboard in integrated BDS mode"
	@printf "  %-24s %s\n" "dashboard-fidelity-build" "Build the optional fidelity dashboard image"
	@printf "  %-24s %s\n" "dashboard-fidelity-up" "Start the optional fidelity dashboard service"
	@printf "  %-24s %s\n" "dashboard-fidelity-down" "Stop the optional fidelity dashboard service"
	@printf "  %-24s %s\n" "monitoring-up" "Start optional Prometheus and Grafana for the integrated node"
	@printf "  %-24s %s\n" "monitoring-down" "Stop optional Prometheus and Grafana for the integrated node"
	@printf "  %-24s %s\n" "monitoring-bds-up" "Start optional Prometheus and Grafana for the integrated BDS stack"
	@printf "  %-24s %s\n" "monitoring-bds-down" "Stop optional Prometheus and Grafana for the integrated BDS stack"
	@printf "  %-24s %s\n" "monitoring-fidelity-up" "Start optional Prometheus and Grafana for the fidelity stack"
	@printf "  %-24s %s\n" "monitoring-fidelity-down" "Stop optional Prometheus and Grafana for the fidelity stack"
	@printf "  %-24s %s\n" "abci-bds-build" "Build the integrated ABCI + BDS stack"
	@printf "  %-24s %s\n" "abci-bds-up" "Start the integrated ABCI + BDS stack"
	@printf "  %-24s %s\n" "abci-bds-down" "Stop the integrated ABCI + BDS stack"
	@printf "  %-24s %s\n" "node-init" "Initialize the CometBFT home via a helper container"
	@printf "  %-24s %s\n" "node-configure" "Render node config via xian-abci's configure helper"
	@printf "  %-24s %s\n" "node-start/node-stop" "Start or stop the integrated node runtime"
	@printf "  %-24s %s\n" "node-start-bds" "Start the node runtime with block-service mode"
	@printf "  %-24s %s\n" "node-status" "Report integrated runtime state as JSON"
	@printf "  %-24s %s\n" "node-status-fidelity" "Report split fidelity runtime state as JSON"
	@printf "  %-24s %s\n" "bds-snapshot-export" "Export a BDS snapshot to XIAN_BDS_SNAPSHOT_PATH"
	@printf "  %-24s %s\n" "bds-snapshot-import" "Import a BDS snapshot from XIAN_BDS_SNAPSHOT_PATH"
	@printf "  %-24s %s\n" "storage-report" "Report host-side chain, BDS, and free-disk usage"
	@printf "  %-24s %s\n" "dev-abci-build/dev-abci-up" "Developer-only ABCI dev stack targets"
	@printf "  %-24s %s\n" "dev-contracting-build" "Developer-only contracting image build"
	@printf "\n  Localnet (multi-node):\n"
	@printf "  %-24s %s\n" "localnet-init" "Generate localnet assets (set XIAN_LOCALNET_TOPOLOGY=integrated|fidelity)"
	@printf "  %-24s %s\n" "localnet-build" "Build the localnet Docker image"
	@printf "  %-24s %s\n" "localnet-up" "Start all localnet nodes"
	@printf "  %-24s %s\n" "localnet-down" "Stop all localnet nodes"
	@printf "  %-24s %s\n" "localnet-status" "Show block height and peer count for each node"
	@printf "  %-24s %s\n" "localnet-dex-bootstrap" "Deploy canonical DEX contracts and a demo pool to a running localnet"
	@printf "  %-24s %s\n" "localnet-up-with-dex" "Start localnet nodes, then bootstrap the canonical DEX"
	@printf "  %-24s %s\n" "localnet-workload" "Run a deterministic workload scenario (counter_basic or dex_mixed)"
	@printf "  %-24s %s\n" "localnet-burst" "Drive the legacy counter_basic workload alias"
	@printf "  %-24s %s\n" "localnet-memwatch" "Sample container memory during localnet tx load"
	@printf "  %-24s %s\n" "localnet-leak-hunt" "Split localnet memory growth by process"
	@printf "  %-24s %s\n" "localnet-e2e" "Run the full layered 5-validator testnet-shaped localnet end-to-end program"
	@printf "  %-24s %s\n" "localnet-vm-report" "Collect the current VM rollout and mismatch report from localnet nodes"
	@printf "  %-24s %s\n" "localnet-vm-e2e" "Run the localnet e2e program with xian_vm_v1 native authority"
	@printf "  %-24s %s\n" "localnet-vm-tps-bench" "Run the VM-native throughput sweep on a tuned 5-node localnet"
	@printf "  %-24s %s\n" "localnet-validator-governance" "Run the 5-validator testnet-shaped governance/state-patch exercise"
	@printf "  %-24s %s\n" "localnet-logs" "Tail logs from all nodes"
	@printf "  %-24s %s\n" "localnet-shell" "Open a shell in node-0"
	@printf "  %-24s %s\n" "localnet-clean" "Stop nodes and delete all localnet data"

print-env:
	@printf "XIAN_CLI_DIR=%s\n" "$(XIAN_CLI_DIR)"
	@printf "XIAN_ABCI_DIR=%s\n" "$(XIAN_ABCI_DIR)"
	@printf "XIAN_CONFIGS_DIR=%s\n" "$(XIAN_CONFIGS_DIR)"
	@printf "XIAN_CONTRACTING_DIR=%s\n" "$(XIAN_CONTRACTING_DIR)"
	@printf "XIAN_PY_DIR=%s\n" "$(XIAN_PY_DIR)"
	@printf "XIAN_STACK_SECRETS_ENV=%s\n" "$(XIAN_STACK_SECRETS_ENV)"
	@printf "XIAN_SERVICE_NODE=%s\n" "$(XIAN_SERVICE_NODE)"
	@printf "XIAN_COMETBFT_HOME=%s\n" "$(XIAN_COMETBFT_HOME)"
	@printf "XIAN_BDS_DATA_DIR=%s\n" "$(XIAN_BDS_DATA_DIR)"
	@printf "XIAN_BDS_HOST=%s\n" "$(XIAN_BDS_HOST)"
	@printf "XIAN_BDS_PORT=%s\n" "$(XIAN_BDS_PORT)"
	@printf "XIAN_BDS_DATABASE=%s\n" "$(XIAN_BDS_DATABASE)"
	@printf "XIAN_BDS_USER=%s\n" "$(XIAN_BDS_USER)"
	@printf "XIAN_BDS_POOL_MIN_SIZE=%s\n" "$(XIAN_BDS_POOL_MIN_SIZE)"
	@printf "XIAN_BDS_POOL_MAX_SIZE=%s\n" "$(XIAN_BDS_POOL_MAX_SIZE)"
	@printf "XIAN_BDS_STATEMENT_TIMEOUT_MS=%s\n" "$(XIAN_BDS_STATEMENT_TIMEOUT_MS)"
	@printf "XIAN_BDS_APPLICATION_NAME=%s\n" "$(XIAN_BDS_APPLICATION_NAME)"
	@printf "XIAN_BDS_SPOOL_DIR=%s\n" "$(XIAN_BDS_SPOOL_DIR)"
	@printf "XIAN_BDS_SPOOL_WARN_ENTRIES=%s\n" "$(XIAN_BDS_SPOOL_WARN_ENTRIES)"
	@printf "XIAN_BDS_SPOOL_WARN_BYTES=%s\n" "$(XIAN_BDS_SPOOL_WARN_BYTES)"
	@printf "XIAN_BDS_DISK_FREE_WARN_BYTES=%s\n" "$(XIAN_BDS_DISK_FREE_WARN_BYTES)"
	@printf "XIAN_BDS_SNAPSHOT_PATH=%s\n" "$(XIAN_BDS_SNAPSHOT_PATH)"
	@printf "XIAN_BDS_SNAPSHOT_FORCE=%s\n" "$(XIAN_BDS_SNAPSHOT_FORCE)"
	@printf "XIAN_BDS_SNAPSHOT_CLEAR_SPOOL=%s\n" "$(XIAN_BDS_SNAPSHOT_CLEAR_SPOOL)"
	@printf "XIAN_STACK_DISK_FREE_WARN_BYTES=%s\n" "$(XIAN_STACK_DISK_FREE_WARN_BYTES)"
	@printf "XIAN_CONTRACTS_DIR=%s\n" "$(XIAN_CONTRACTS_DIR)"
	@printf "XIAN_COMETBFT_VERSION=%s\n" "$(XIAN_COMETBFT_VERSION)"
	@printf "XIAN_S6_OVERLAY_VERSION=%s\n" "$(XIAN_S6_OVERLAY_VERSION)"
	@printf "XIAN_S6_VERBOSITY=%s\n" "$(XIAN_S6_VERBOSITY)"
	@printf "XIAN_TRACER_MODE=%s\n" "$(XIAN_TRACER_MODE)"
	@printf "XIAN_NODE_IMAGE_MODE=%s\n" "$(XIAN_NODE_IMAGE_MODE)"
	@printf "XIAN_NODE_INTEGRATED_IMAGE=%s\n" "$(XIAN_NODE_INTEGRATED_IMAGE)"
	@printf "XIAN_NODE_SPLIT_IMAGE=%s\n" "$(XIAN_NODE_SPLIT_IMAGE)"
	@printf "XIAN_PUBLIC_RPC_ENABLED=%s\n" "$(XIAN_PUBLIC_RPC_ENABLED)"
	@printf "XIAN_PUBLIC_QUERY_ENABLED=%s\n" "$(XIAN_PUBLIC_QUERY_ENABLED)"
	@printf "XIAN_PUBLIC_METRICS_ENABLED=%s\n" "$(XIAN_PUBLIC_METRICS_ENABLED)"
	@printf "XIAN_COMETBFT_RPC_HOST=%s\n" "$(XIAN_COMETBFT_RPC_HOST)"
	@printf "XIAN_COMETBFT_RPC_PORT=%s\n" "$(XIAN_COMETBFT_RPC_PORT)"
	@printf "XIAN_COMETBFT_METRICS_HOST=%s\n" "$(XIAN_COMETBFT_METRICS_HOST)"
	@printf "XIAN_COMETBFT_METRICS_PORT=%s\n" "$(XIAN_COMETBFT_METRICS_PORT)"
	@printf "XIAN_APP_METRICS_ENABLED=%s\n" "$(XIAN_APP_METRICS_ENABLED)"
	@printf "XIAN_APP_METRICS_LISTEN_HOST=%s\n" "$(XIAN_APP_METRICS_LISTEN_HOST)"
	@printf "XIAN_APP_METRICS_HOST=%s\n" "$(XIAN_APP_METRICS_HOST)"
	@printf "XIAN_APP_METRICS_PORT=%s\n" "$(XIAN_APP_METRICS_PORT)"
	@printf "XIAN_APP_METRICS_BDS_REFRESH_SECONDS=%s\n" "$(XIAN_APP_METRICS_BDS_REFRESH_SECONDS)"
	@printf "XIAN_PERF_ENABLED=%s\n" "$(XIAN_PERF_ENABLED)"
	@printf "XIAN_PERF_RECENT_BLOCKS=%s\n" "$(XIAN_PERF_RECENT_BLOCKS)"
	@printf "XIAN_PROMETHEUS_IMAGE=%s\n" "$(XIAN_PROMETHEUS_IMAGE)"
	@printf "XIAN_PROMETHEUS_CONFIG=%s\n" "$(XIAN_PROMETHEUS_CONFIG)"
	@printf "XIAN_PROMETHEUS_HOST=%s\n" "$(XIAN_PROMETHEUS_HOST)"
	@printf "XIAN_PROMETHEUS_PORT=%s\n" "$(XIAN_PROMETHEUS_PORT)"
	@printf "XIAN_GRAFANA_IMAGE=%s\n" "$(XIAN_GRAFANA_IMAGE)"
	@printf "XIAN_GRAFANA_HOST=%s\n" "$(XIAN_GRAFANA_HOST)"
	@printf "XIAN_GRAFANA_PORT=%s\n" "$(XIAN_GRAFANA_PORT)"
	@printf "XIAN_STACK_TOPOLOGY=%s\n" "$(XIAN_STACK_TOPOLOGY)"
	@printf "XIAN_DOCKER_ABCI_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_ABCI_MEMORY_LIMIT)"
	@printf "XIAN_DASHBOARD_HOST=%s\n" "$(XIAN_DASHBOARD_HOST)"
	@printf "XIAN_DASHBOARD_PORT=%s\n" "$(XIAN_DASHBOARD_PORT)"
	@printf "XIAN_DOCKER_ABCI_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_ABCI_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_ABCI_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_ABCI_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_ABCI_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_ABCI_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_ABCI_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_ABCI_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_ABCI_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_ABCI_NOFILE_HARD)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD)"
	@printf "XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT)"
	@printf "XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_DASHBOARD_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_DASHBOARD_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_DASHBOARD_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_DASHBOARD_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_DASHBOARD_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_DASHBOARD_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_DASHBOARD_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_DASHBOARD_NOFILE_HARD)"
	@printf "XIAN_DOCKER_POSTGRES_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_POSTGRES_MEMORY_LIMIT)"
	@printf "XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_POSTGRES_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_POSTGRES_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_POSTGRES_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_POSTGRES_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_POSTGRES_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_POSTGRES_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_POSTGRES_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_POSTGRES_NOFILE_HARD)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT)"
	@printf "XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD=%s\n" "$(XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD)"
	@printf "XIAN_POSTGRAPHILE_USER=%s\n" "$(XIAN_POSTGRAPHILE_USER)"
	@printf "XIAN_POSTGRAPHILE_HOST=%s\n" "$(XIAN_POSTGRAPHILE_HOST)"
	@printf "XIAN_POSTGRAPHILE_PORT=%s\n" "$(XIAN_POSTGRAPHILE_PORT)"
	@printf "XIAN_LOCALNET_TOPOLOGY=%s\n" "$(XIAN_LOCALNET_TOPOLOGY)"
	@printf "XIAN_LOCALNET_NODE_MEMORY_LIMIT=%s\n" "$(XIAN_LOCALNET_NODE_MEMORY_LIMIT)"
	@printf "XIAN_LOCALNET_NODE_MEMORY_RESERVATION=%s\n" "$(XIAN_LOCALNET_NODE_MEMORY_RESERVATION)"
	@printf "XIAN_LOCALNET_NODE_MEMORY_SWAP=%s\n" "$(XIAN_LOCALNET_NODE_MEMORY_SWAP)"
	@printf "XIAN_LOCALNET_NODE_PIDS_LIMIT=%s\n" "$(XIAN_LOCALNET_NODE_PIDS_LIMIT)"
	@printf "XIAN_LOCALNET_NODE_NOFILE_SOFT=%s\n" "$(XIAN_LOCALNET_NODE_NOFILE_SOFT)"
	@printf "XIAN_LOCALNET_NODE_NOFILE_HARD=%s\n" "$(XIAN_LOCALNET_NODE_NOFILE_HARD)"
	@printf "XIAN_LOCALNET_ABCI_MEMORY_LIMIT=%s\n" "$(XIAN_LOCALNET_ABCI_MEMORY_LIMIT)"
	@printf "XIAN_LOCALNET_ABCI_MEMORY_RESERVATION=%s\n" "$(XIAN_LOCALNET_ABCI_MEMORY_RESERVATION)"
	@printf "XIAN_LOCALNET_ABCI_MEMORY_SWAP=%s\n" "$(XIAN_LOCALNET_ABCI_MEMORY_SWAP)"
	@printf "XIAN_LOCALNET_ABCI_PIDS_LIMIT=%s\n" "$(XIAN_LOCALNET_ABCI_PIDS_LIMIT)"
	@printf "XIAN_LOCALNET_ABCI_NOFILE_SOFT=%s\n" "$(XIAN_LOCALNET_ABCI_NOFILE_SOFT)"
	@printf "XIAN_LOCALNET_ABCI_NOFILE_HARD=%s\n" "$(XIAN_LOCALNET_ABCI_NOFILE_HARD)"
	@printf "XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT=%s\n" "$(XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT)"
	@printf "XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION=%s\n" "$(XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION)"
	@printf "XIAN_LOCALNET_COMETBFT_MEMORY_SWAP=%s\n" "$(XIAN_LOCALNET_COMETBFT_MEMORY_SWAP)"
	@printf "XIAN_LOCALNET_COMETBFT_PIDS_LIMIT=%s\n" "$(XIAN_LOCALNET_COMETBFT_PIDS_LIMIT)"
	@printf "XIAN_LOCALNET_COMETBFT_NOFILE_SOFT=%s\n" "$(XIAN_LOCALNET_COMETBFT_NOFILE_SOFT)"
	@printf "XIAN_LOCALNET_COMETBFT_NOFILE_HARD=%s\n" "$(XIAN_LOCALNET_COMETBFT_NOFILE_HARD)"
	@printf "XIAN_LOCALNET_TRACER_MODE=%s\n" "$(XIAN_LOCALNET_TRACER_MODE)"

validate:
	./scripts/validate-stack.sh

release-safety:
	./scripts/release-safety.sh

smoke:
	./scripts/smoke-stack.sh

smoke-cli:
	./scripts/smoke-cli.sh

guard-stack-security:
	@bash -lc 'source ./scripts/stack-env.sh && export_stack_env >/dev/null'

prepare-dirs: guard-stack-security
	mkdir -p "$(XIAN_COMETBFT_HOME)" "$(XIAN_BDS_DATA_DIR)" "$(XIAN_CONTRACTS_DIR)" "$(dir $(XIAN_BDS_SNAPSHOT_PATH))"


# Dev-only contracting commands
dev-contracting-shell: dev-contracting-up

dev-contracting-up: prepare-dirs
	$(CONTRACTING_COMPOSE) up -d
	$(CONTRACTING_COMPOSE) exec contracting /bin/bash

dev-contracting-build: prepare-dirs
	$(CONTRACTING_COMPOSE) build

dev-contracting-down:
	$(CONTRACTING_COMPOSE) down


# Dev-only ABCI commands
dev-abci-build: prepare-dirs
	$(ABCI_DEV_COMPOSE) build --no-cache

dev-abci-up: prepare-dirs
	$(ABCI_DEV_COMPOSE) up -d

dev-abci-down:
	$(ABCI_DEV_COMPOSE) down

dev-abci-shell: dev-abci-up
	$(ABCI_DEV_COMPOSE) exec abci /bin/bash


# Runtime container commands
abci-build: prepare-dirs
	$(ABCI_COMPOSE) build --no-cache abci

abci-up: prepare-dirs
	$(call maybe_pull_integrated,$(ABCI_COMPOSE),abci)
	$(ABCI_COMPOSE) up -d $(NODE_UP_BUILD_FLAG) abci

abci-down:
	$(ABCI_COMPOSE) down --remove-orphans

abci-fidelity-build: prepare-dirs
	$(ABCI_FIDELITY_COMPOSE) build --no-cache abci-app cometbft

abci-fidelity-up: prepare-dirs
	$(call maybe_pull_fidelity,$(ABCI_FIDELITY_COMPOSE),abci-app cometbft)
	$(ABCI_FIDELITY_COMPOSE) up -d $(NODE_UP_BUILD_FLAG) abci-app cometbft

abci-fidelity-down:
	$(ABCI_FIDELITY_COMPOSE) down --remove-orphans

dashboard-build: prepare-dirs
	$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml build --no-cache dashboard

dashboard-up: prepare-dirs
	$(call maybe_pull_integrated,$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml,abci dashboard)
	$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml up -d $(DASHBOARD_UP_BUILD_FLAG) abci dashboard

dashboard-down:
	$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml rm -sf dashboard

dashboard-bds-up: prepare-dirs
	$(call maybe_pull_integrated,$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml -f docker-compose-abci-bds.yml,abci dashboard)
	$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml -f docker-compose-abci-bds.yml up -d $(DASHBOARD_UP_BUILD_FLAG) abci postgres postgraphile dashboard

dashboard-bds-down:
	$(DOCKER_COMPOSE) --profile integrated --profile dashboard-integrated -f docker-compose-abci.yml -f docker-compose-abci-bds.yml rm -sf dashboard

dashboard-fidelity-build: prepare-dirs
	$(DOCKER_COMPOSE) --profile fidelity --profile dashboard-fidelity -f docker-compose-abci.yml build --no-cache dashboard-fidelity

dashboard-fidelity-up: prepare-dirs
	$(call maybe_pull_fidelity,$(DOCKER_COMPOSE) --profile fidelity --profile dashboard-fidelity -f docker-compose-abci.yml,abci-app cometbft dashboard-fidelity)
	$(DOCKER_COMPOSE) --profile fidelity --profile dashboard-fidelity -f docker-compose-abci.yml up -d $(DASHBOARD_UP_BUILD_FLAG) abci-app cometbft dashboard-fidelity

dashboard-fidelity-down:
	$(DOCKER_COMPOSE) --profile fidelity --profile dashboard-fidelity -f docker-compose-abci.yml rm -sf dashboard-fidelity

monitoring-up: prepare-dirs
	$(call maybe_pull_integrated,XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/integrated.yml $(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml,abci)
	XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/integrated.yml $(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml up -d $(NODE_UP_BUILD_FLAG) abci prometheus grafana

monitoring-down:
	$(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml rm -sf prometheus grafana

monitoring-bds-up: prepare-dirs
	$(call maybe_pull_integrated,XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/integrated.yml $(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-abci-bds.yml -f docker-compose-monitoring.yml,abci)
	XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/integrated.yml $(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-abci-bds.yml -f docker-compose-monitoring.yml up -d $(NODE_UP_BUILD_FLAG) abci postgres postgraphile prometheus grafana

monitoring-bds-down:
	$(DOCKER_COMPOSE) --profile integrated --profile monitoring -f docker-compose-abci.yml -f docker-compose-abci-bds.yml -f docker-compose-monitoring.yml rm -sf prometheus grafana

monitoring-fidelity-up: prepare-dirs
	$(call maybe_pull_fidelity,XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/fidelity.yml $(DOCKER_COMPOSE) --profile fidelity --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml,abci-app cometbft)
	XIAN_PROMETHEUS_CONFIG=./monitoring/prometheus/fidelity.yml $(DOCKER_COMPOSE) --profile fidelity --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml up -d $(NODE_UP_BUILD_FLAG) abci-app cometbft prometheus grafana

monitoring-fidelity-down:
	$(DOCKER_COMPOSE) --profile fidelity --profile monitoring -f docker-compose-abci.yml -f docker-compose-monitoring.yml rm -sf prometheus grafana

dev-base-abci-shell:
	$(ABCI_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci


# ABCI BDS Commands
abci-bds-build abci-bds-up dashboard-bds-up monitoring-bds-up bds-postgres-up bds-snapshot-export bds-snapshot-import node-start-bds: XIAN_SERVICE_NODE=1

abci-bds-build: prepare-dirs
	$(ABCI_BDS_COMPOSE) build --no-cache abci postgres postgraphile

abci-bds-up: prepare-dirs
	$(call maybe_pull_integrated,$(ABCI_BDS_COMPOSE),abci)
	$(call maybe_build_postgraphile,$(ABCI_BDS_COMPOSE))
	$(ABCI_BDS_COMPOSE) up -d $(NODE_UP_BUILD_FLAG)

abci-bds-down:
	$(ABCI_BDS_COMPOSE) down --remove-orphans

dev-bds-abci-shell:
	$(ABCI_BDS_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci

wipe-bds:
	rm -rf "$(XIAN_BDS_DATA_DIR)"/*


# Node runtime commands
node-wipe:
	$(ABCI_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci -lc "rm -rf /root/.cometbft/xian && cometbft unsafe-reset-all"

node-wipe-all: wipe-bds node-wipe

node-reset: node-wipe node-init

node-stop:
	$(ABCI_COMPOSE) down --remove-orphans

node-start:
	$(call maybe_pull_integrated,$(ABCI_COMPOSE),abci)
	$(ABCI_COMPOSE) up -d $(NODE_UP_BUILD_FLAG) abci

node-start-bds:
	$(call maybe_pull_integrated,$(ABCI_BDS_COMPOSE),abci)
	$(call maybe_build_postgraphile,$(ABCI_BDS_COMPOSE))
	$(ABCI_BDS_COMPOSE) up -d $(NODE_UP_BUILD_FLAG)

node-init:
	$(ABCI_COMPOSE) run --rm --no-deps --entrypoint cometbft abci init

node-configure: guard-stack-security
	$(ABCI_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci -lc "metrics_flag='--metrics-enabled'; if [ '$(XIAN_APP_METRICS_ENABLED)' = '0' ]; then metrics_flag='--no-metrics-enabled'; fi; xian-configure-node --tracer-mode $(XIAN_TRACER_MODE) $$metrics_flag --metrics-host $(XIAN_APP_METRICS_LISTEN_HOST) --metrics-port $(XIAN_APP_METRICS_PORT) --metrics-bds-refresh-seconds $(XIAN_APP_METRICS_BDS_REFRESH_SECONDS) --bds-host $(XIAN_BDS_HOST) --bds-port $(XIAN_BDS_PORT) --bds-database $(XIAN_BDS_DATABASE) --bds-user $(XIAN_BDS_USER) --bds-password $(XIAN_BDS_PASSWORD) --bds-pool-min-size $(XIAN_BDS_POOL_MIN_SIZE) --bds-pool-max-size $(XIAN_BDS_POOL_MAX_SIZE) --bds-statement-timeout-ms $(XIAN_BDS_STATEMENT_TIMEOUT_MS) --bds-application-name $(XIAN_BDS_APPLICATION_NAME) $(if $(XIAN_BDS_SPOOL_DIR),--bds-spool-dir $(XIAN_BDS_SPOOL_DIR),) --bds-spool-warn-entries $(XIAN_BDS_SPOOL_WARN_ENTRIES) --bds-spool-warn-bytes $(XIAN_BDS_SPOOL_WARN_BYTES) --bds-disk-free-warn-bytes $(XIAN_BDS_DISK_FREE_WARN_BYTES) ${CONFIGURE_ARGS}"

node-id:
	$(ABCI_COMPOSE) run --rm --no-deps --entrypoint cometbft abci show-node-id

node-status:
	@./scripts/node-status.sh

node-status-fidelity:
	@XIAN_STACK_TOPOLOGY=fidelity ./scripts/node-status.sh

bds-postgres-up: prepare-dirs
	$(ABCI_BDS_COMPOSE) up -d postgres
	@until $(ABCI_BDS_COMPOSE) exec -T postgres pg_isready -U "$(XIAN_BDS_USER)" -d "$(XIAN_BDS_DATABASE)" >/dev/null 2>&1; do \
		sleep 1; \
	done

bds-snapshot-export: bds-postgres-up
	@case "$(abspath $(XIAN_BDS_SNAPSHOT_PATH))" in \
		"$(abspath $(XIAN_COMETBFT_HOME))"/*) ;; \
		*) echo "ERROR: XIAN_BDS_SNAPSHOT_PATH must live under XIAN_COMETBFT_HOME so the stack container can access it." >&2; exit 1 ;; \
	esac
	$(ABCI_BDS_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci -lc "xian-bds-snapshot export --output-path $(XIAN_BDS_SNAPSHOT_CONTAINER_PATH) $(if $(filter 1,$(XIAN_BDS_SNAPSHOT_FORCE)),--force,)"

bds-snapshot-import: bds-postgres-up
	@case "$(abspath $(XIAN_BDS_SNAPSHOT_PATH))" in \
		"$(abspath $(XIAN_COMETBFT_HOME))"/*) ;; \
		*) echo "ERROR: XIAN_BDS_SNAPSHOT_PATH must live under XIAN_COMETBFT_HOME so the stack container can access it." >&2; exit 1 ;; \
	esac
	@test -f "$(XIAN_BDS_SNAPSHOT_PATH)" || (echo "ERROR: BDS snapshot archive not found at $(XIAN_BDS_SNAPSHOT_PATH)" >&2; exit 1)
	$(ABCI_BDS_COMPOSE) run --rm --no-deps --entrypoint /bin/bash abci -lc "xian-bds-snapshot import --input-path $(XIAN_BDS_SNAPSHOT_CONTAINER_PATH) $(if $(filter 1,$(XIAN_BDS_SNAPSHOT_CLEAR_SPOOL)),--clear-spool,)"

storage-report:
	@python3 ./scripts/storage-report.py


# ── Localnet (multi-node) ────────────────────────────────────────────

localnet-init:
	uv run --project "$(XIAN_ABCI_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-init.py --nodes $(LOCALNET_NODES) --topology $(XIAN_LOCALNET_TOPOLOGY) --genesis-network "$(XIAN_LOCALNET_GENESIS_NETWORK)" --clean

localnet-build:
	$(LOCALNET_COMPOSE) build $(LOCALNET_BUILD_SERVICE)

localnet-up:
	@if [ ! -f docker-compose-localnet.yml ]; then \
		echo "ERROR: Run 'make localnet-init' first." >&2; exit 1; \
	fi
	$(LOCALNET_COMPOSE) up -d

localnet-down:
	@if [ -f docker-compose-localnet.yml ]; then \
		$(LOCALNET_COMPOSE) down; \
	fi

localnet-status:
	@./scripts/localnet-status.sh

localnet-dex-bootstrap:
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-dex-bootstrap.py \
		--dex-contracts-dir "$(XIAN_DEX_CONTRACTS_DIR)" \
		$(if $(XIAN_DEX_BOOTSTRAP_RPC_URL),--rpc-url "$(XIAN_DEX_BOOTSTRAP_RPC_URL)",) \
		$(if $(XIAN_DEX_BOOTSTRAP_CHAIN_ID),--chain-id "$(XIAN_DEX_BOOTSTRAP_CHAIN_ID)",) \
		--validator-key-path "$(XIAN_DEX_VALIDATOR_KEY_PATH)" \
		$(if $(filter 1,$(LOCALNET_DEX_DEPLOY_HELPER)),--deploy-helper,--no-deploy-helper) \
		$(if $(filter 1,$(LOCALNET_DEX_SEED_DEMO_POOL)),--seed-demo-pool,--no-seed-demo-pool) \
		$(if $(filter 1,$(LOCALNET_DEX_TOP_UP_LIQUIDITY)),--top-up-liquidity,--no-top-up-liquidity) \
		$(if $(filter 1,$(LOCALNET_DEX_EMIT_TEST_SWAP)),--emit-test-swap,--no-emit-test-swap) \
		--demo-token-contract "$(LOCALNET_DEX_DEMO_TOKEN_CONTRACT)" \
		--demo-lp-contract "$(LOCALNET_DEX_DEMO_LP_CONTRACT)" \
		--demo-token-name "$(LOCALNET_DEX_DEMO_TOKEN_NAME)" \
		--demo-token-symbol "$(LOCALNET_DEX_DEMO_TOKEN_SYMBOL)" \
		--demo-token-supply $(LOCALNET_DEX_DEMO_TOKEN_SUPPLY) \
		--demo-token-precision $(LOCALNET_DEX_DEMO_TOKEN_PRECISION) \
		--liquidity-currency-amount $(LOCALNET_DEX_LIQUIDITY_CURRENCY_AMOUNT) \
		--liquidity-demo-token-amount $(LOCALNET_DEX_LIQUIDITY_DEMO_TOKEN_AMOUNT) \
		--test-swap-amount $(LOCALNET_DEX_TEST_SWAP_AMOUNT)

localnet-up-with-dex: localnet-up localnet-dex-bootstrap

localnet-workload:
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-workload.py \
		--scenario "$(LOCALNET_WORKLOAD_SCENARIO)" \
		--seed "$(LOCALNET_WORKLOAD_SEED)" \
		--counter-ops $(LOCALNET_COUNTER_OPS) \
		--dex-rounds $(LOCALNET_DEX_ROUNDS) \
		--throughput-ops $(LOCALNET_THROUGHPUT_OPS) \
		--wallet-count $(LOCALNET_WORKLOAD_WALLET_COUNT) \
		--submit-workers $(LOCALNET_SUBMIT_WORKERS) \
		--broadcast-mode "$(LOCALNET_BROADCAST_MODE)" \
		--receipt-timeout-seconds $(LOCALNET_RECEIPT_TIMEOUT_SECONDS) \
		--heavy-rounds $(LOCALNET_HEAVY_ROUNDS) \
		--state-sample-nodes $(LOCALNET_STATE_SAMPLE_NODES) \
		--app-hash-window $(LOCALNET_APP_HASH_WINDOW) \
		--receipt-resolution "$(LOCALNET_RECEIPT_RESOLUTION)" \
		--receipt-workers $(LOCALNET_RECEIPT_WORKERS) \
		$(if $(filter 0,$(LOCALNET_WORKLOAD_MEASURE_MEMORY)),--no-measure-memory,--measure-memory)

localnet-burst:
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-workload.py \
		--scenario counter_basic \
		--seed "$(LOCALNET_WORKLOAD_SEED)" \
		--counter-ops $(LOCALNET_COUNTER_OPS) \
		--state-sample-nodes $(LOCALNET_STATE_SAMPLE_NODES) \
		--app-hash-window $(LOCALNET_APP_HASH_WINDOW) \
		--receipt-resolution "$(LOCALNET_RECEIPT_RESOLUTION)" \
		--receipt-workers $(LOCALNET_RECEIPT_WORKERS) \
		$(if $(filter 0,$(LOCALNET_WORKLOAD_MEASURE_MEMORY)),--no-measure-memory,--measure-memory)

localnet-memwatch:
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-memwatch.py $(LOCALNET_MEMWATCH_MINUTES)

localnet-leak-hunt:
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-leak-hunt.py $(LOCALNET_LEAK_HUNT_MINUTES)

localnet-e2e:
	XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED="$(LOCALNET_E2E_PARALLEL_EXECUTION_ENABLED)" \
	XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS="$(LOCALNET_E2E_PARALLEL_EXECUTION_WORKERS)" \
	XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS="$(LOCALNET_E2E_PARALLEL_EXECUTION_MIN_TRANSACTIONS)" \
	uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-e2e.py \
		$(if $(filter 0,$(LOCALNET_E2E_BOOTSTRAP)),--no-bootstrap,--bootstrap) \
		$(if $(filter 1,$(LOCALNET_E2E_BUILD)),--build,--no-build) \
		--nodes $(LOCALNET_E2E_NODES) \
		--topology "$(XIAN_LOCALNET_TOPOLOGY)" \
		--genesis-network "$(LOCALNET_E2E_GENESIS_NETWORK)" \
		--bds-node-index $(LOCALNET_E2E_BDS_NODE_INDEX) \
		--port-offset $(LOCALNET_E2E_PORT_OFFSET) \
		--seed "$(LOCALNET_E2E_SEED)" \
		--log-level "$(LOCALNET_E2E_LOG_LEVEL)" \
		--execution-mode "$(XIAN_LOCALNET_EXECUTION_MODE)" \
		--execution-bytecode-version "$(XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION)" \
		--execution-gas-schedule "$(XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE)" \
		--execution-authority "$(XIAN_LOCALNET_EXECUTION_AUTHORITY)" \
		--execution-shadow-tracer-mode "$(XIAN_LOCALNET_EXECUTION_SHADOW_TRACER_MODE)" \
		--rpc-timeout-seconds $(LOCALNET_E2E_RPC_TIMEOUT_SECONDS) \
		--state-sample-nodes $(LOCALNET_E2E_STATE_SAMPLE_NODES) \
		--app-hash-window $(LOCALNET_E2E_APP_HASH_WINDOW) \
		--receipt-workers $(LOCALNET_E2E_RECEIPT_WORKERS) \
		--periodic-rounds $(LOCALNET_E2E_PERIODIC_ROUNDS) \
		--periodic-interval-seconds $(LOCALNET_E2E_PERIODIC_INTERVAL_SECONDS) \
		--burst-counter-ops $(LOCALNET_E2E_BURST_COUNTER_OPS) \
		--dex-rounds $(LOCALNET_E2E_DEX_ROUNDS) \
		--chaos-cycles $(LOCALNET_E2E_CHAOS_CYCLES) \
		--chaos-load-transactions $(LOCALNET_E2E_CHAOS_LOAD_TRANSACTIONS) \
		--soak-duration-seconds $(LOCALNET_E2E_SOAK_DURATION_SECONDS) \
		--soak-batch-size $(LOCALNET_E2E_SOAK_BATCH_SIZE) \
		--soak-progress-interval-seconds $(LOCALNET_E2E_SOAK_PROGRESS_INTERVAL_SECONDS) \
		--vm-max-shadow-mismatches $(LOCALNET_VM_REPORT_MAX_SHADOW_MISMATCHES)

localnet-vm-report:
	python3 ./scripts/localnet_vm_rollout.py \
		--timeout-seconds 5 \
		--max-shadow-mismatches $(LOCALNET_VM_REPORT_MAX_SHADOW_MISMATCHES)

localnet-vm-e2e:
	XIAN_LOCALNET_EXECUTION_MODE="$(LOCALNET_VM_E2E_EXECUTION_MODE)" \
	XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION="$(LOCALNET_VM_E2E_BYTECODE_VERSION)" \
	XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE="$(LOCALNET_VM_E2E_GAS_SCHEDULE)" \
	XIAN_LOCALNET_EXECUTION_AUTHORITY="$(LOCALNET_VM_E2E_AUTHORITY)" \
	LOCALNET_E2E_PARALLEL_EXECUTION_MIN_TRANSACTIONS="$(LOCALNET_VM_E2E_PARALLEL_EXECUTION_MIN_TRANSACTIONS)" \
	$(MAKE) localnet-e2e

localnet-vm-tps-bench:
	@bash -lc 'set -euo pipefail; \
		trap "cd \"$(CURDIR)\" && $(MAKE) localnet-down >/dev/null" EXIT; \
		cd "$(CURDIR)"; \
		XIAN_LOCALNET_PARALLEL_EXECUTION_ENABLED="$(LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_ENABLED)" \
		XIAN_LOCALNET_PARALLEL_EXECUTION_WORKERS="$(LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_WORKERS)" \
		XIAN_LOCALNET_PARALLEL_EXECUTION_MIN_TRANSACTIONS="$(LOCALNET_TPS_BENCH_PARALLEL_EXECUTION_MIN_TRANSACTIONS)" \
		XIAN_LOCALNET_PROFILE="$(LOCALNET_TPS_BENCH_PROFILE)" \
		XIAN_LOCALNET_EXECUTION_MODE="$(LOCALNET_VM_E2E_EXECUTION_MODE)" \
		XIAN_LOCALNET_EXECUTION_BYTECODE_VERSION="$(LOCALNET_VM_E2E_BYTECODE_VERSION)" \
		XIAN_LOCALNET_EXECUTION_GAS_SCHEDULE="$(LOCALNET_VM_E2E_GAS_SCHEDULE)" \
		XIAN_LOCALNET_EXECUTION_AUTHORITY="$(LOCALNET_VM_E2E_AUTHORITY)" \
		XIAN_LOCALNET_PORT_OFFSET="$(LOCALNET_TPS_BENCH_PORT_OFFSET)" \
		LOCALNET_NODES="$(LOCALNET_TPS_BENCH_NODES)" \
		$(MAKE) localnet-init localnet-build localnet-up; \
		uv run --project "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-tps-bench.py \
			--scenario "$(LOCALNET_TPS_BENCH_SCENARIO)" \
			--ops $(LOCALNET_TPS_BENCH_OPS) \
			--wallet-count $(LOCALNET_TPS_BENCH_WALLET_COUNT) \
			--submit-workers $(LOCALNET_TPS_BENCH_SUBMIT_WORKERS) \
			--receipt-workers $(LOCALNET_TPS_BENCH_RECEIPT_WORKERS) \
			--receipt-timeout-seconds $(LOCALNET_TPS_BENCH_RECEIPT_TIMEOUT_SECONDS) \
			--heavy-rounds $(LOCALNET_TPS_BENCH_HEAVY_ROUNDS); \
	'

localnet-validator-governance:
	uv run --project "$(XIAN_ABCI_DIR)" --with "$(XIAN_PY_DIR)" --python "$(XIAN_STACK_PYTHON)" python3 ./scripts/localnet-validator-governance.py \
		$(if $(filter 0,$(LOCALNET_VALIDATOR_GOVERNANCE_BOOTSTRAP)),--no-bootstrap,--bootstrap) \
		$(if $(filter 1,$(LOCALNET_VALIDATOR_GOVERNANCE_BUILD)),--build,--no-build) \
		--nodes $(LOCALNET_VALIDATOR_GOVERNANCE_NODES) \
		--topology "$(XIAN_LOCALNET_TOPOLOGY)" \
		--genesis-network "$(LOCALNET_VALIDATOR_GOVERNANCE_GENESIS_NETWORK)" \
		--port-offset $(LOCALNET_VALIDATOR_GOVERNANCE_PORT_OFFSET) \
		--seed "$(LOCALNET_VALIDATOR_GOVERNANCE_SEED)" \
		--tracer-mode "$(XIAN_LOCALNET_TRACER_MODE)" \
		--log-level "$(LOCALNET_VALIDATOR_GOVERNANCE_LOG_LEVEL)" \
		--rpc-timeout-seconds $(LOCALNET_VALIDATOR_GOVERNANCE_RPC_TIMEOUT_SECONDS)

localnet-logs:
	$(LOCALNET_COMPOSE) logs -f --tail=50

localnet-shell:
	@service="$$(python3 -c 'import json, pathlib; data=json.loads(pathlib.Path(".localnet/network.json").read_text()); print("node-0-abci" if data.get("topology") == "fidelity" else "node-0")')"; \
	$(LOCALNET_COMPOSE) exec "$$service" /bin/bash

localnet-clean: localnet-down
	@if [ "$(FORCE)" != "1" ]; then \
		echo "localnet-clean will delete .localnet/ and docker-compose-localnet.yml."; \
		echo "All localnet state (keys, data, logs) will be lost."; \
		echo "Re-run with FORCE=1 to confirm: make localnet-clean FORCE=1"; \
		exit 1; \
	fi
	rm -rf .localnet
	rm -f docker-compose-localnet.yml
