global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: xian_abci
    static_configs:
      - targets:
          - abci:9108

  - job_name: xian_cometbft
    static_configs:
      - targets:
          - abci:26660
