from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

STACK_DIR = Path(__file__).resolve().parent.parent

SUPPORTED_INTENTKIT_NETWORK_IDS = (
    "xian-mainnet",
    "xian-testnet",
    "xian-devnet",
    "xian-localnet",
)
INTENTKIT_CORE_SERVICES = (
    "db",
    "rustfs",
    "redis",
    "api",
    "autonomous",
    "scheduler",
    "frontend",
)
_GENERATED_HEADER = (
    "# Generated by xian-stack for stack-managed xian-intentkit.\n"
    "# Prefer editing xian-stack env vars over editing this file directly.\n"
)


def display_host(host: str) -> str:
    if host == "0.0.0.0":
        return "127.0.0.1"
    if host == "::":
        return "::1"
    return host


def resolve_repo_dir(
    name: str,
    env_var: str,
    *,
    env: dict[str, str] | None = None,
) -> Path:
    source_env = os.environ if env is None else env
    explicit = source_env.get(env_var)
    if explicit:
        return Path(explicit).expanduser().resolve()
    return (STACK_DIR.parent / name).resolve()


def resolve_intentkit_repo_dir(*, env: dict[str, str] | None = None) -> Path:
    return resolve_repo_dir("xian-intentkit", "XIAN_INTENTKIT_DIR", env=env)


def resolve_intentkit_deployment_dir(
    *, env: dict[str, str] | None = None
) -> Path:
    return resolve_intentkit_repo_dir(env=env) / "deployment"


def resolve_intentkit_env_file(*, env: dict[str, str] | None = None) -> Path:
    source_env = os.environ if env is None else env
    explicit = source_env.get("XIAN_INTENTKIT_ENV_FILE")
    if explicit:
        return Path(explicit).expanduser().resolve()
    return resolve_intentkit_deployment_dir(env=env) / ".env"


def require_intentkit_repo(*, env: dict[str, str] | None = None) -> Path:
    repo_dir = resolve_intentkit_repo_dir(env=env)
    deployment_dir = repo_dir / "deployment"
    env_example = repo_dir / ".env.example"
    docker_compose = deployment_dir / "docker-compose.yml"

    missing = [
        path
        for path in (repo_dir, deployment_dir, env_example, docker_compose)
        if not path.exists()
    ]
    if missing:
        missing_list = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(
            "xian-intentkit integration requires the sibling repo and its "
            f"deployment files. Missing: {missing_list}"
        )
    return repo_dir


def validate_intentkit_network_id(network_id: str) -> str:
    normalized = (network_id or "").strip().lower()
    if normalized not in SUPPORTED_INTENTKIT_NETWORK_IDS:
        supported = ", ".join(SUPPORTED_INTENTKIT_NETWORK_IDS)
        raise ValueError(
            f"unsupported xian-intentkit network id '{network_id}'; "
            f"supported values: {supported}"
        )
    return normalized


def _network_env_prefix(network_id: str) -> str:
    return validate_intentkit_network_id(network_id).upper().replace("-", "_")


def _rpc_base_url(rpc_status_url: str) -> str:
    parsed = urlsplit(rpc_status_url)
    path = parsed.path
    if path.endswith("/status"):
        path = path[: -len("/status")]
    path = path.rstrip("/")
    return urlunsplit((parsed.scheme, parsed.netloc, path, "", ""))


def _intentkit_rpc_url(rpc_status_url: str) -> str:
    parsed = urlsplit(_rpc_base_url(rpc_status_url))
    hostname = parsed.hostname or "127.0.0.1"
    if hostname in {"127.0.0.1", "localhost", "0.0.0.0", "::1", "::"}:
        hostname = "host.docker.internal"
    netloc = hostname
    if parsed.port is not None:
        netloc = f"{hostname}:{parsed.port}"
    return urlunsplit((parsed.scheme or "http", netloc, parsed.path, "", ""))


def _parse_env_entries(path: Path) -> list[tuple[str, ...]]:
    entries: list[tuple[str, ...]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.lstrip().startswith("#") or "=" not in line:
            entries.append(("raw", line))
            continue
        key, value = line.split("=", 1)
        entries.append(("key", key.strip(), value.strip()))
    return entries


def _decode_env_value(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        return ""
    if stripped.startswith('"') and stripped.endswith('"'):
        try:
            decoded = json.loads(stripped)
            if isinstance(decoded, str):
                return decoded
        except json.JSONDecodeError:
            return stripped[1:-1]
    if stripped.startswith("'") and stripped.endswith("'"):
        return stripped[1:-1]
    return stripped


def _read_env_mapping(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    mapping: dict[str, str] = {}
    for entry in _parse_env_entries(path):
        if entry[0] == "key":
            _, key, value = entry
            mapping[key] = _decode_env_value(value)
    return mapping


def _render_env_value(value: str) -> str:
    if value == "":
        return ""
    safe_chars = set(
        "abcdefghijklmnopqrstuvwxyz"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "0123456789"
        "_-./:@?&=%+,"
    )
    if all(char in safe_chars for char in value):
        return value
    return json.dumps(value)


def intentkit_endpoints(
    *,
    bind_host: str,
    frontend_port: int,
    api_port: int,
    public_host: str | None = None,
    s3_port: int = 39000,
) -> dict[str, str]:
    public_host = public_host or display_host(bind_host)
    frontend_base = f"http://{public_host}:{frontend_port}"
    api_base = f"http://{public_host}:{api_port}"
    return {
        "intentkit": frontend_base,
        "intentkit_api": api_base,
        "intentkit_api_health": f"{api_base}/health",
        "intentkit_static": f"http://{public_host}:{s3_port}/static",
    }


def _derived_env_values(
    *,
    network_id: str,
    chain_id: str,
    rpc_status_url: str,
    bind_host: str,
    frontend_port: int,
    api_port: int,
) -> dict[str, str]:
    prefix = _network_env_prefix(network_id)
    endpoints = intentkit_endpoints(
        bind_host=bind_host,
        frontend_port=frontend_port,
        api_port=api_port,
    )
    derived = {
        "ENV": os.environ.get("XIAN_INTENTKIT_ENV", "local"),
        "DEBUG": os.environ.get("XIAN_INTENTKIT_DEBUG", "true"),
        "APP_BASE_URL": endpoints["intentkit"],
        "AWS_S3_CDN_URL": endpoints["intentkit_static"],
        f"{prefix}_RPC_URL": _intentkit_rpc_url(rpc_status_url),
        f"{prefix}_CHAIN_ID": chain_id,
    }

    price_strategy = os.environ.get("XIAN_INTENTKIT_PRICE_STRATEGY")
    if price_strategy:
        derived[f"{prefix}_PRICE_STRATEGY"] = price_strategy
    fixed_usd = os.environ.get("XIAN_INTENTKIT_PRICE_FIXED_USD")
    if fixed_usd:
        derived[f"{prefix}_PRICE_FIXED_USD"] = fixed_usd
    solana_mint = os.environ.get("XIAN_INTENTKIT_PRICE_SOLANA_MINT")
    if solana_mint:
        derived[f"{prefix}_PRICE_SOLANA_MINT"] = solana_mint
    market_url = os.environ.get("XIAN_INTENTKIT_PRICE_MARKET_URL")
    if market_url:
        derived[f"{prefix}_PRICE_MARKET_URL"] = market_url

    return derived


def ensure_intentkit_env(
    *,
    network_id: str,
    chain_id: str,
    rpc_status_url: str,
    bind_host: str,
    frontend_port: int,
    api_port: int,
    env: dict[str, str] | None = None,
) -> dict[str, str]:
    source_env = os.environ if env is None else env
    repo_dir = require_intentkit_repo(env=source_env)
    env_example = repo_dir / ".env.example"
    env_file = resolve_intentkit_env_file(env=source_env)
    env_file.parent.mkdir(parents=True, exist_ok=True)

    template_entries = _parse_env_entries(env_example)
    template_keys = {
        entry[1] for entry in template_entries if entry and entry[0] == "key"
    }
    current_values = _read_env_mapping(env_file)
    derived_values = _derived_env_values(
        network_id=network_id,
        chain_id=chain_id,
        rpc_status_url=rpc_status_url,
        bind_host=bind_host,
        frontend_port=frontend_port,
        api_port=api_port,
    )

    lines = [_GENERATED_HEADER.rstrip("\n")]
    resolved_keys: set[str] = set()
    for entry in template_entries:
        if entry[0] == "raw":
            lines.append(entry[1])
            continue
        _, key, default_value = entry
        resolved_keys.add(key)
        value = derived_values.get(key)
        if value is None:
            value = source_env.get(key)
        if value is None:
            value = current_values.get(key, _decode_env_value(default_value))
        lines.append(f"{key}={_render_env_value(value)}")

    extra_keys = [
        key
        for key in current_values
        if key not in template_keys and key not in resolved_keys
    ]
    derived_only_keys = [
        key
        for key in derived_values
        if key not in template_keys and key not in resolved_keys
    ]

    if extra_keys or derived_only_keys:
        lines.append("")
    if extra_keys:
        lines.append("# Preserved custom values")
        for key in sorted(extra_keys):
            lines.append(f"{key}={_render_env_value(current_values[key])}")
    if derived_only_keys:
        lines.append("# Xian stack derived values")
        for key in sorted(derived_only_keys):
            lines.append(f"{key}={_render_env_value(derived_values[key])}")

    env_file.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    endpoints = intentkit_endpoints(
        bind_host=bind_host,
        frontend_port=frontend_port,
        api_port=api_port,
        public_host=source_env.get("XIAN_INTENTKIT_PUBLIC_HOST"),
        s3_port=int(source_env.get("XIAN_INTENTKIT_S3_PORT", "39000")),
    )
    return {
        "intentkit_repo_dir": str(repo_dir),
        "intentkit_env_file": str(env_file),
        "intentkit_network_id": validate_intentkit_network_id(network_id),
        "intentkit_chain_id": chain_id,
        **endpoints,
    }


def _compose_cmd(*args: str, env: dict[str, str] | None = None) -> list[str]:
    source_env = os.environ if env is None else env
    repo_dir = require_intentkit_repo(env=source_env)
    deployment_dir = repo_dir / "deployment"
    return [
        "docker",
        "compose",
        "--project-name",
        source_env.get("XIAN_INTENTKIT_PROJECT_NAME", "xian-intentkit-stack"),
        "--project-directory",
        str(deployment_dir),
        "-f",
        str(deployment_dir / "docker-compose.yml"),
        "-f",
        str(STACK_DIR / "docker-compose-intentkit.yml"),
        *args,
    ]


def run_intentkit_compose(
    *args: str,
    capture_output: bool = False,
    check: bool = True,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    source_env = os.environ.copy()
    if env is not None:
        source_env.update(env)
    intentkit_dir = resolve_intentkit_repo_dir(env=source_env)
    xian_py_dir = resolve_repo_dir("xian-py", "XIAN_PY_DIR", env=source_env)
    xian_contracting_dir = resolve_repo_dir(
        "xian-contracting",
        "XIAN_CONTRACTING_DIR",
        env=source_env,
    )
    source_env.setdefault("XIAN_INTENTKIT_DIR", str(intentkit_dir))
    source_env.setdefault("XIAN_PY_DIR", str(xian_py_dir))
    source_env.setdefault("XIAN_CONTRACTING_DIR", str(xian_contracting_dir))
    source_env.setdefault(
        "XIAN_INTENTKIT_STACK_DOCKERFILE",
        str((STACK_DIR / "docker" / "intentkit.Dockerfile").resolve()),
    )
    return subprocess.run(
        _compose_cmd(*args, env=source_env),
        cwd=STACK_DIR,
        check=check,
        capture_output=capture_output,
        text=True,
        env=source_env,
    )


def start_intentkit_runtime(
    *, env: dict[str, str] | None = None
) -> dict[str, object]:
    run_intentkit_compose(
        "up",
        "-d",
        "--build",
        *INTENTKIT_CORE_SERVICES,
        env=env,
    )
    return get_intentkit_status(env=env)


def stop_intentkit_runtime(
    *, env: dict[str, str] | None = None
) -> dict[str, object]:
    run_intentkit_compose("down", "--remove-orphans", env=env)
    return {
        "intentkit_project_name": (os.environ if env is None else env).get(
            "XIAN_INTENTKIT_PROJECT_NAME", "xian-intentkit-stack"
        ),
        "intentkit_stopped": True,
    }


def _parse_compose_ps(output: str) -> list[dict[str, object]]:
    stripped = output.strip()
    if not stripped:
        return []
    try:
        payload = json.loads(stripped)
    except json.JSONDecodeError:
        items = []
        for line in stripped.splitlines():
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            if isinstance(item, dict):
                items.append(item)
        return items
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        return [payload]
    return []


def get_intentkit_status(
    *, env: dict[str, str] | None = None
) -> dict[str, object]:
    result = run_intentkit_compose(
        "ps",
        "--format",
        "json",
        capture_output=True,
        env=env,
    )
    services = _parse_compose_ps(result.stdout)
    normalized_services = []
    running_services: set[str] = set()

    for item in services:
        service = str(item.get("Service") or item.get("Name") or "")
        state = str(item.get("State") or "").lower()
        status = str(item.get("Status") or "")
        normalized_services.append(
            {
                "service": service,
                "state": state,
                "status": status,
                "publishers": item.get("Publishers"),
            }
        )
        if state == "running":
            running_services.add(service)

    expected = set(INTENTKIT_CORE_SERVICES)
    return {
        "intentkit_project_name": (os.environ if env is None else env).get(
            "XIAN_INTENTKIT_PROJECT_NAME", "xian-intentkit-stack"
        ),
        "intentkit_running": expected.issubset(running_services),
        "intentkit_services": normalized_services,
    }
