#!/usr/bin/env bash

stack_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

resolve_repo_dir() {
  local name="$1"
  local explicit_value="${2:-}"
  local sibling_path="${stack_root}/../${name}"

  if [[ -n "${explicit_value}" ]]; then
    printf '%s\n' "${explicit_value}"
    return
  fi

  if [[ -d "${sibling_path}" ]]; then
    printf '%s\n' "${sibling_path}"
    return
  fi

  printf '%s\n' "${sibling_path}"
}

export_stack_env() {
  export XIAN_CLI_DIR="${XIAN_CLI_DIR:-$(resolve_repo_dir xian-cli "${XIAN_CLI_DIR:-}")}"
  export XIAN_ABCI_DIR="${XIAN_ABCI_DIR:-$(resolve_repo_dir xian-abci "${XIAN_ABCI_DIR:-}")}"
  export XIAN_CONFIGS_DIR="${XIAN_CONFIGS_DIR:-$(resolve_repo_dir xian-configs "${XIAN_CONFIGS_DIR:-}")}"
  export XIAN_CONTRACTING_DIR="${XIAN_CONTRACTING_DIR:-$(resolve_repo_dir xian-contracting "${XIAN_CONTRACTING_DIR:-}")}"
  export XIAN_PY_DIR="${XIAN_PY_DIR:-$(resolve_repo_dir xian-py "${XIAN_PY_DIR:-}")}"
  export XIAN_INTENTKIT_DIR="${XIAN_INTENTKIT_DIR:-$(resolve_repo_dir xian-intentkit "${XIAN_INTENTKIT_DIR:-}")}"
  export XIAN_INTENTKIT_ENV="${XIAN_INTENTKIT_ENV:-local}"
  export XIAN_INTENTKIT_DEBUG="${XIAN_INTENTKIT_DEBUG:-true}"
  export XIAN_INTENTKIT_RELEASE="${XIAN_INTENTKIT_RELEASE:-local}"
  export XIAN_INTENTKIT_PROJECT_NAME="${XIAN_INTENTKIT_PROJECT_NAME:-xian-intentkit-stack}"
  export XIAN_INTENTKIT_ENV_FILE="${XIAN_INTENTKIT_ENV_FILE:-${XIAN_INTENTKIT_DIR}/deployment/.env}"
  export XIAN_INTENTKIT_STACK_DOCKERFILE="${XIAN_INTENTKIT_STACK_DOCKERFILE:-${stack_root}/docker/intentkit.Dockerfile}"
  export XIAN_INTENTKIT_HOST="${XIAN_INTENTKIT_HOST:-127.0.0.1}"
  export XIAN_INTENTKIT_PUBLIC_HOST="${XIAN_INTENTKIT_PUBLIC_HOST:-127.0.0.1}"
  export XIAN_INTENTKIT_PORT="${XIAN_INTENTKIT_PORT:-38000}"
  export XIAN_INTENTKIT_API_PORT="${XIAN_INTENTKIT_API_PORT:-38080}"
  export XIAN_INTENTKIT_S3_PORT="${XIAN_INTENTKIT_S3_PORT:-39000}"
  export XIAN_INTENTKIT_PRICE_STRATEGY="${XIAN_INTENTKIT_PRICE_STRATEGY:-}"
  export XIAN_INTENTKIT_PRICE_FIXED_USD="${XIAN_INTENTKIT_PRICE_FIXED_USD:-}"
  export XIAN_INTENTKIT_PRICE_SOLANA_MINT="${XIAN_INTENTKIT_PRICE_SOLANA_MINT:-}"
  export XIAN_INTENTKIT_PRICE_MARKET_URL="${XIAN_INTENTKIT_PRICE_MARKET_URL:-}"
  export XIAN_COMETBFT_HOME="${XIAN_COMETBFT_HOME:-${stack_root}/.cometbft}"
  export XIAN_BDS_DATA_DIR="${XIAN_BDS_DATA_DIR:-${stack_root}/.bds.db}"
  export XIAN_BDS_HOST="${XIAN_BDS_HOST:-postgres}"
  export XIAN_BDS_PORT="${XIAN_BDS_PORT:-5432}"
  export XIAN_BDS_DATABASE="${XIAN_BDS_DATABASE:-xian}"
  export XIAN_BDS_USER="${XIAN_BDS_USER:-xian}"
  export XIAN_BDS_PASSWORD="${XIAN_BDS_PASSWORD:-xian}"
  export XIAN_BDS_POOL_MIN_SIZE="${XIAN_BDS_POOL_MIN_SIZE:-1}"
  export XIAN_BDS_POOL_MAX_SIZE="${XIAN_BDS_POOL_MAX_SIZE:-10}"
  export XIAN_BDS_STATEMENT_TIMEOUT_MS="${XIAN_BDS_STATEMENT_TIMEOUT_MS:-0}"
  export XIAN_BDS_APPLICATION_NAME="${XIAN_BDS_APPLICATION_NAME:-xian-bds}"
  export XIAN_BDS_SPOOL_DIR="${XIAN_BDS_SPOOL_DIR:-}"
  export XIAN_BDS_SPOOL_WARN_ENTRIES="${XIAN_BDS_SPOOL_WARN_ENTRIES:-256}"
  export XIAN_BDS_SPOOL_WARN_BYTES="${XIAN_BDS_SPOOL_WARN_BYTES:-536870912}"
  export XIAN_BDS_DISK_FREE_WARN_BYTES="${XIAN_BDS_DISK_FREE_WARN_BYTES:-2147483648}"
  export XIAN_STACK_DISK_FREE_WARN_BYTES="${XIAN_STACK_DISK_FREE_WARN_BYTES:-10737418240}"
  export XIAN_CONTRACTS_DIR="${XIAN_CONTRACTS_DIR:-${stack_root}/contracts}"
  export XIAN_COMETBFT_VERSION="${XIAN_COMETBFT_VERSION:-0.38.21}"
  export XIAN_S6_OVERLAY_VERSION="${XIAN_S6_OVERLAY_VERSION:-3.2.1.0}"
  export XIAN_S6_VERBOSITY="${XIAN_S6_VERBOSITY:-1}"
  export XIAN_TRACER_MODE="${XIAN_TRACER_MODE:-python_line_v1}"
  export XIAN_NODE_IMAGE_MODE="${XIAN_NODE_IMAGE_MODE:-local_build}"
  export XIAN_NODE_INTEGRATED_IMAGE="${XIAN_NODE_INTEGRATED_IMAGE:-xian-node-integrated:local}"
  export XIAN_NODE_SPLIT_IMAGE="${XIAN_NODE_SPLIT_IMAGE:-xian-node-split:local}"
  export XIAN_COMETBFT_RPC_HOST="${XIAN_COMETBFT_RPC_HOST:-0.0.0.0}"
  export XIAN_COMETBFT_RPC_PORT="${XIAN_COMETBFT_RPC_PORT:-26657}"
  export XIAN_COMETBFT_P2P_HOST="${XIAN_COMETBFT_P2P_HOST:-0.0.0.0}"
  export XIAN_COMETBFT_P2P_PORT="${XIAN_COMETBFT_P2P_PORT:-26656}"
  export XIAN_COMETBFT_METRICS_HOST="${XIAN_COMETBFT_METRICS_HOST:-0.0.0.0}"
  export XIAN_COMETBFT_METRICS_PORT="${XIAN_COMETBFT_METRICS_PORT:-26660}"
  export XIAN_APP_METRICS_ENABLED="${XIAN_APP_METRICS_ENABLED:-1}"
  export XIAN_APP_METRICS_LISTEN_HOST="${XIAN_APP_METRICS_LISTEN_HOST:-0.0.0.0}"
  export XIAN_APP_METRICS_HOST="${XIAN_APP_METRICS_HOST:-127.0.0.1}"
  export XIAN_APP_METRICS_PORT="${XIAN_APP_METRICS_PORT:-9108}"
  export XIAN_APP_METRICS_BDS_REFRESH_SECONDS="${XIAN_APP_METRICS_BDS_REFRESH_SECONDS:-5.0}"
  export XIAN_PERF_ENABLED="${XIAN_PERF_ENABLED:-1}"
  export XIAN_PERF_RECENT_BLOCKS="${XIAN_PERF_RECENT_BLOCKS:-64}"
  export XIAN_PROMETHEUS_IMAGE="${XIAN_PROMETHEUS_IMAGE:-prom/prometheus:v3.10.0}"
  export XIAN_PROMETHEUS_CONFIG="${XIAN_PROMETHEUS_CONFIG:-./monitoring/prometheus/integrated.yml}"
  export XIAN_PROMETHEUS_HOST="${XIAN_PROMETHEUS_HOST:-127.0.0.1}"
  export XIAN_PROMETHEUS_PORT="${XIAN_PROMETHEUS_PORT:-9090}"
  export XIAN_GRAFANA_IMAGE="${XIAN_GRAFANA_IMAGE:-grafana/grafana:12.2.0}"
  export XIAN_GRAFANA_HOST="${XIAN_GRAFANA_HOST:-127.0.0.1}"
  export XIAN_GRAFANA_PORT="${XIAN_GRAFANA_PORT:-3000}"
  export XIAN_STACK_TOPOLOGY="${XIAN_STACK_TOPOLOGY:-integrated}"
  export XIAN_DOCKER_ABCI_MEMORY_LIMIT="${XIAN_DOCKER_ABCI_MEMORY_LIMIT:-2048m}"
  export XIAN_DOCKER_ABCI_MEMORY_RESERVATION="${XIAN_DOCKER_ABCI_MEMORY_RESERVATION:-1024m}"
  export XIAN_DOCKER_ABCI_MEMORY_SWAP="${XIAN_DOCKER_ABCI_MEMORY_SWAP:-2048m}"
  export XIAN_DOCKER_ABCI_PIDS_LIMIT="${XIAN_DOCKER_ABCI_PIDS_LIMIT:-512}"
  export XIAN_DOCKER_ABCI_NOFILE_SOFT="${XIAN_DOCKER_ABCI_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_ABCI_NOFILE_HARD="${XIAN_DOCKER_ABCI_NOFILE_HARD:-65536}"
  export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT="${XIAN_DOCKER_FIDELITY_ABCI_MEMORY_LIMIT:-1536m}"
  export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION="${XIAN_DOCKER_FIDELITY_ABCI_MEMORY_RESERVATION:-768m}"
  export XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP="${XIAN_DOCKER_FIDELITY_ABCI_MEMORY_SWAP:-1536m}"
  export XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT="${XIAN_DOCKER_FIDELITY_ABCI_PIDS_LIMIT:-384}"
  export XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT="${XIAN_DOCKER_FIDELITY_ABCI_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD="${XIAN_DOCKER_FIDELITY_ABCI_NOFILE_HARD:-65536}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT="${XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_LIMIT:-768m}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION="${XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_RESERVATION:-256m}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP="${XIAN_DOCKER_FIDELITY_COMETBFT_MEMORY_SWAP:-768m}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT="${XIAN_DOCKER_FIDELITY_COMETBFT_PIDS_LIMIT:-256}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT="${XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD="${XIAN_DOCKER_FIDELITY_COMETBFT_NOFILE_HARD:-65536}"
  export XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT="${XIAN_DOCKER_DASHBOARD_MEMORY_LIMIT:-512m}"
  export XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION="${XIAN_DOCKER_DASHBOARD_MEMORY_RESERVATION:-256m}"
  export XIAN_DOCKER_DASHBOARD_MEMORY_SWAP="${XIAN_DOCKER_DASHBOARD_MEMORY_SWAP:-512m}"
  export XIAN_DOCKER_DASHBOARD_PIDS_LIMIT="${XIAN_DOCKER_DASHBOARD_PIDS_LIMIT:-256}"
  export XIAN_DOCKER_DASHBOARD_NOFILE_SOFT="${XIAN_DOCKER_DASHBOARD_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_DASHBOARD_NOFILE_HARD="${XIAN_DOCKER_DASHBOARD_NOFILE_HARD:-65536}"
  export XIAN_DASHBOARD_HOST="${XIAN_DASHBOARD_HOST:-127.0.0.1}"
  export XIAN_DASHBOARD_PORT="${XIAN_DASHBOARD_PORT:-8080}"
  export XIAN_DOCKER_POSTGRES_MEMORY_LIMIT="${XIAN_DOCKER_POSTGRES_MEMORY_LIMIT:-1024m}"
  export XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION="${XIAN_DOCKER_POSTGRES_MEMORY_RESERVATION:-512m}"
  export XIAN_DOCKER_POSTGRES_MEMORY_SWAP="${XIAN_DOCKER_POSTGRES_MEMORY_SWAP:-1024m}"
  export XIAN_DOCKER_POSTGRES_PIDS_LIMIT="${XIAN_DOCKER_POSTGRES_PIDS_LIMIT:-256}"
  export XIAN_DOCKER_POSTGRES_NOFILE_SOFT="${XIAN_DOCKER_POSTGRES_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_POSTGRES_NOFILE_HARD="${XIAN_DOCKER_POSTGRES_NOFILE_HARD:-65536}"
  export XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT="${XIAN_DOCKER_POSTGRAPHILE_MEMORY_LIMIT:-768m}"
  export XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION="${XIAN_DOCKER_POSTGRAPHILE_MEMORY_RESERVATION:-256m}"
  export XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP="${XIAN_DOCKER_POSTGRAPHILE_MEMORY_SWAP:-768m}"
  export XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT="${XIAN_DOCKER_POSTGRAPHILE_PIDS_LIMIT:-256}"
  export XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT="${XIAN_DOCKER_POSTGRAPHILE_NOFILE_SOFT:-65536}"
  export XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD="${XIAN_DOCKER_POSTGRAPHILE_NOFILE_HARD:-65536}"
  export XIAN_LOCALNET_TOPOLOGY="${XIAN_LOCALNET_TOPOLOGY:-integrated}"
  export XIAN_LOCALNET_TRACER_MODE="${XIAN_LOCALNET_TRACER_MODE:-${XIAN_TRACER_MODE}}"
  export XIAN_LOCALNET_NODE_MEMORY_LIMIT="${XIAN_LOCALNET_NODE_MEMORY_LIMIT:-1536m}"
  export XIAN_LOCALNET_NODE_MEMORY_RESERVATION="${XIAN_LOCALNET_NODE_MEMORY_RESERVATION:-1024m}"
  export XIAN_LOCALNET_NODE_MEMORY_SWAP="${XIAN_LOCALNET_NODE_MEMORY_SWAP:-1536m}"
  export XIAN_LOCALNET_NODE_PIDS_LIMIT="${XIAN_LOCALNET_NODE_PIDS_LIMIT:-512}"
  export XIAN_LOCALNET_NODE_NOFILE_SOFT="${XIAN_LOCALNET_NODE_NOFILE_SOFT:-65536}"
  export XIAN_LOCALNET_NODE_NOFILE_HARD="${XIAN_LOCALNET_NODE_NOFILE_HARD:-65536}"
  export XIAN_LOCALNET_ABCI_MEMORY_LIMIT="${XIAN_LOCALNET_ABCI_MEMORY_LIMIT:-1024m}"
  export XIAN_LOCALNET_ABCI_MEMORY_RESERVATION="${XIAN_LOCALNET_ABCI_MEMORY_RESERVATION:-768m}"
  export XIAN_LOCALNET_ABCI_MEMORY_SWAP="${XIAN_LOCALNET_ABCI_MEMORY_SWAP:-1024m}"
  export XIAN_LOCALNET_ABCI_PIDS_LIMIT="${XIAN_LOCALNET_ABCI_PIDS_LIMIT:-384}"
  export XIAN_LOCALNET_ABCI_NOFILE_SOFT="${XIAN_LOCALNET_ABCI_NOFILE_SOFT:-65536}"
  export XIAN_LOCALNET_ABCI_NOFILE_HARD="${XIAN_LOCALNET_ABCI_NOFILE_HARD:-65536}"
  export XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT="${XIAN_LOCALNET_COMETBFT_MEMORY_LIMIT:-512m}"
  export XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION="${XIAN_LOCALNET_COMETBFT_MEMORY_RESERVATION:-256m}"
  export XIAN_LOCALNET_COMETBFT_MEMORY_SWAP="${XIAN_LOCALNET_COMETBFT_MEMORY_SWAP:-512m}"
  export XIAN_LOCALNET_COMETBFT_PIDS_LIMIT="${XIAN_LOCALNET_COMETBFT_PIDS_LIMIT:-256}"
  export XIAN_LOCALNET_COMETBFT_NOFILE_SOFT="${XIAN_LOCALNET_COMETBFT_NOFILE_SOFT:-65536}"
  export XIAN_LOCALNET_COMETBFT_NOFILE_HARD="${XIAN_LOCALNET_COMETBFT_NOFILE_HARD:-65536}"
}

require_stack_paths() {
  local required_paths=(
    "${XIAN_CLI_DIR}"
    "${XIAN_ABCI_DIR}"
    "${XIAN_CONFIGS_DIR}"
    "${XIAN_CONTRACTING_DIR}"
    "${XIAN_PY_DIR}"
    "${XIAN_CONTRACTS_DIR}"
  )

  for path in "${required_paths[@]}"; do
    if [[ ! -d "${path}" ]]; then
      printf 'missing required directory: %s\n' "${path}" >&2
      return 1
    fi
  done
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    printf 'docker is required but not installed\n' >&2
    return 1
  fi

  docker compose version >/dev/null
}

require_uv() {
  if ! command -v uv >/dev/null 2>&1; then
    printf 'uv is required but not installed\n' >&2
    return 1
  fi
}

prepare_stack_dirs() {
  mkdir -p "${XIAN_COMETBFT_HOME}" "${XIAN_BDS_DATA_DIR}" "${XIAN_CONTRACTS_DIR}"
}
