apiVersion: 1

datasources:
  - name: Xian Prometheus
    orgId: 1
    uid: xian-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
